/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivilegeZonesRouteImport } from './routes/privilege-zones'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as GroupManagementRouteImport } from './routes/group-management'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DownloadCollectorsRouteImport } from './routes/download-collectors'
import { Route as ApiExplorerRouteImport } from './routes/api-explorer'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PrivilegeZonesIndexRouteImport } from './routes/privilege-zones/index'
import { Route as AdministrationIndexRouteImport } from './routes/administration/index'
import { Route as PrivilegeZonesHistoryRouteImport } from './routes/privilege-zones/history'
import { Route as AdministrationSsoConfigurationRouteImport } from './routes/administration/sso-configuration'
import { Route as AdministrationOpengraphManagementRouteImport } from './routes/administration/opengraph-management'
import { Route as AdministrationManageUsersRouteImport } from './routes/administration/manage-users'
import { Route as AdministrationFileIngestRouteImport } from './routes/administration/file-ingest'
import { Route as AdministrationEarlyAccessFeaturesRouteImport } from './routes/administration/early-access-features'
import { Route as AdministrationDatabaseManagementRouteImport } from './routes/administration/database-management'
import { Route as AdministrationDataQualityRouteImport } from './routes/administration/data-quality'
import { Route as AdministrationBloodhoundConfigurationRouteImport } from './routes/administration/bloodhound-configuration'
import { Route as authUserDisabledRouteImport } from './routes/(auth)/user-disabled'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authExpiredPasswordRouteImport } from './routes/(auth)/expired-password'
import { Route as authChangepasswordRouteImport } from './routes/(auth)/changepassword'
import { Route as PrivilegeZonesZonesZoneIdDetailsRouteImport } from './routes/privilege-zones/zones.$zoneId.details'
import { Route as PrivilegeZonesLabelsLabelIdSaveRouteImport } from './routes/privilege-zones/labels.$labelId.save'
import { Route as PrivilegeZonesLabelsLabelIdDetailsRouteImport } from './routes/privilege-zones/labels.$labelId.details'
import { Route as PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRouteImport } from './routes/privilege-zones/zones.$zoneId.rules.$ruleId.details'
import { Route as PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRouteImport } from './routes/privilege-zones/labels.$labelId.rules.$ruleId.save'
import { Route as PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRouteImport } from './routes/privilege-zones/labels.$labelId.rules.$ruleId.details'
import { Route as PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRouteImport } from './routes/privilege-zones/zones.$zoneId.rules.$ruleId.objects.$objectId.details'
import { Route as PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRouteImport } from './routes/privilege-zones/labels.$labelId.rules.$ruleId.objects.$objectId.details'

const PrivilegeZonesRoute = PrivilegeZonesRouteImport.update({
  id: '/privilege-zones',
  path: '/privilege-zones',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupManagementRoute = GroupManagementRouteImport.update({
  id: '/group-management',
  path: '/group-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadCollectorsRoute = DownloadCollectorsRouteImport.update({
  id: '/download-collectors',
  path: '/download-collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplorerRoute = ApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegeZonesIndexRoute = PrivilegeZonesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivilegeZonesRoute,
} as any)
const AdministrationIndexRoute = AdministrationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministrationRoute,
} as any)
const PrivilegeZonesHistoryRoute = PrivilegeZonesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PrivilegeZonesRoute,
} as any)
const AdministrationSsoConfigurationRoute =
  AdministrationSsoConfigurationRouteImport.update({
    id: '/sso-configuration',
    path: '/sso-configuration',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationOpengraphManagementRoute =
  AdministrationOpengraphManagementRouteImport.update({
    id: '/opengraph-management',
    path: '/opengraph-management',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationManageUsersRoute =
  AdministrationManageUsersRouteImport.update({
    id: '/manage-users',
    path: '/manage-users',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationFileIngestRoute =
  AdministrationFileIngestRouteImport.update({
    id: '/file-ingest',
    path: '/file-ingest',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationEarlyAccessFeaturesRoute =
  AdministrationEarlyAccessFeaturesRouteImport.update({
    id: '/early-access-features',
    path: '/early-access-features',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationDatabaseManagementRoute =
  AdministrationDatabaseManagementRouteImport.update({
    id: '/database-management',
    path: '/database-management',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationDataQualityRoute =
  AdministrationDataQualityRouteImport.update({
    id: '/data-quality',
    path: '/data-quality',
    getParentRoute: () => AdministrationRoute,
  } as any)
const AdministrationBloodhoundConfigurationRoute =
  AdministrationBloodhoundConfigurationRouteImport.update({
    id: '/bloodhound-configuration',
    path: '/bloodhound-configuration',
    getParentRoute: () => AdministrationRoute,
  } as any)
const authUserDisabledRoute = authUserDisabledRouteImport.update({
  id: '/(auth)/user-disabled',
  path: '/user-disabled',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authExpiredPasswordRoute = authExpiredPasswordRouteImport.update({
  id: '/(auth)/expired-password',
  path: '/expired-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authChangepasswordRoute = authChangepasswordRouteImport.update({
  id: '/(auth)/changepassword',
  path: '/changepassword',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegeZonesZonesZoneIdDetailsRoute =
  PrivilegeZonesZonesZoneIdDetailsRouteImport.update({
    id: '/zones/$zoneId/details',
    path: '/zones/$zoneId/details',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesLabelsLabelIdSaveRoute =
  PrivilegeZonesLabelsLabelIdSaveRouteImport.update({
    id: '/labels/$labelId/save',
    path: '/labels/$labelId/save',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesLabelsLabelIdDetailsRoute =
  PrivilegeZonesLabelsLabelIdDetailsRouteImport.update({
    id: '/labels/$labelId/details',
    path: '/labels/$labelId/details',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute =
  PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRouteImport.update({
    id: '/zones/$zoneId/rules/$ruleId/details',
    path: '/zones/$zoneId/rules/$ruleId/details',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute =
  PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRouteImport.update({
    id: '/labels/$labelId/rules/$ruleId/save',
    path: '/labels/$labelId/rules/$ruleId/save',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute =
  PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRouteImport.update({
    id: '/labels/$labelId/rules/$ruleId/details',
    path: '/labels/$labelId/rules/$ruleId/details',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute =
  PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRouteImport.update({
    id: '/zones/$zoneId/rules/$ruleId/objects/$objectId/details',
    path: '/zones/$zoneId/rules/$ruleId/objects/$objectId/details',
    getParentRoute: () => PrivilegeZonesRoute,
  } as any)
const PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute =
  PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRouteImport.update(
    {
      id: '/labels/$labelId/rules/$ruleId/objects/$objectId/details',
      path: '/labels/$labelId/rules/$ruleId/objects/$objectId/details',
      getParentRoute: () => PrivilegeZonesRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/api-explorer': typeof ApiExplorerRoute
  '/download-collectors': typeof DownloadCollectorsRoute
  '/explore': typeof ExploreRoute
  '/group-management': typeof GroupManagementRoute
  '/my-profile': typeof MyProfileRoute
  '/privilege-zones': typeof PrivilegeZonesRouteWithChildren
  '/changepassword': typeof authChangepasswordRoute
  '/expired-password': typeof authExpiredPasswordRoute
  '/login': typeof authLoginRoute
  '/user-disabled': typeof authUserDisabledRoute
  '/administration/bloodhound-configuration': typeof AdministrationBloodhoundConfigurationRoute
  '/administration/data-quality': typeof AdministrationDataQualityRoute
  '/administration/database-management': typeof AdministrationDatabaseManagementRoute
  '/administration/early-access-features': typeof AdministrationEarlyAccessFeaturesRoute
  '/administration/file-ingest': typeof AdministrationFileIngestRoute
  '/administration/manage-users': typeof AdministrationManageUsersRoute
  '/administration/opengraph-management': typeof AdministrationOpengraphManagementRoute
  '/administration/sso-configuration': typeof AdministrationSsoConfigurationRoute
  '/privilege-zones/history': typeof PrivilegeZonesHistoryRoute
  '/administration/': typeof AdministrationIndexRoute
  '/privilege-zones/': typeof PrivilegeZonesIndexRoute
  '/privilege-zones/labels/$labelId/details': typeof PrivilegeZonesLabelsLabelIdDetailsRoute
  '/privilege-zones/labels/$labelId/save': typeof PrivilegeZonesLabelsLabelIdSaveRoute
  '/privilege-zones/zones/$zoneId/details': typeof PrivilegeZonesZonesZoneIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/save': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/api-explorer': typeof ApiExplorerRoute
  '/download-collectors': typeof DownloadCollectorsRoute
  '/explore': typeof ExploreRoute
  '/group-management': typeof GroupManagementRoute
  '/my-profile': typeof MyProfileRoute
  '/changepassword': typeof authChangepasswordRoute
  '/expired-password': typeof authExpiredPasswordRoute
  '/login': typeof authLoginRoute
  '/user-disabled': typeof authUserDisabledRoute
  '/administration/bloodhound-configuration': typeof AdministrationBloodhoundConfigurationRoute
  '/administration/data-quality': typeof AdministrationDataQualityRoute
  '/administration/database-management': typeof AdministrationDatabaseManagementRoute
  '/administration/early-access-features': typeof AdministrationEarlyAccessFeaturesRoute
  '/administration/file-ingest': typeof AdministrationFileIngestRoute
  '/administration/manage-users': typeof AdministrationManageUsersRoute
  '/administration/opengraph-management': typeof AdministrationOpengraphManagementRoute
  '/administration/sso-configuration': typeof AdministrationSsoConfigurationRoute
  '/privilege-zones/history': typeof PrivilegeZonesHistoryRoute
  '/administration': typeof AdministrationIndexRoute
  '/privilege-zones': typeof PrivilegeZonesIndexRoute
  '/privilege-zones/labels/$labelId/details': typeof PrivilegeZonesLabelsLabelIdDetailsRoute
  '/privilege-zones/labels/$labelId/save': typeof PrivilegeZonesLabelsLabelIdSaveRoute
  '/privilege-zones/zones/$zoneId/details': typeof PrivilegeZonesZonesZoneIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/save': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/administration': typeof AdministrationRouteWithChildren
  '/api-explorer': typeof ApiExplorerRoute
  '/download-collectors': typeof DownloadCollectorsRoute
  '/explore': typeof ExploreRoute
  '/group-management': typeof GroupManagementRoute
  '/my-profile': typeof MyProfileRoute
  '/privilege-zones': typeof PrivilegeZonesRouteWithChildren
  '/(auth)/changepassword': typeof authChangepasswordRoute
  '/(auth)/expired-password': typeof authExpiredPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/user-disabled': typeof authUserDisabledRoute
  '/administration/bloodhound-configuration': typeof AdministrationBloodhoundConfigurationRoute
  '/administration/data-quality': typeof AdministrationDataQualityRoute
  '/administration/database-management': typeof AdministrationDatabaseManagementRoute
  '/administration/early-access-features': typeof AdministrationEarlyAccessFeaturesRoute
  '/administration/file-ingest': typeof AdministrationFileIngestRoute
  '/administration/manage-users': typeof AdministrationManageUsersRoute
  '/administration/opengraph-management': typeof AdministrationOpengraphManagementRoute
  '/administration/sso-configuration': typeof AdministrationSsoConfigurationRoute
  '/privilege-zones/history': typeof PrivilegeZonesHistoryRoute
  '/administration/': typeof AdministrationIndexRoute
  '/privilege-zones/': typeof PrivilegeZonesIndexRoute
  '/privilege-zones/labels/$labelId/details': typeof PrivilegeZonesLabelsLabelIdDetailsRoute
  '/privilege-zones/labels/$labelId/save': typeof PrivilegeZonesLabelsLabelIdSaveRoute
  '/privilege-zones/zones/$zoneId/details': typeof PrivilegeZonesZonesZoneIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/save': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute
  '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute
  '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details': typeof PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/administration'
    | '/api-explorer'
    | '/download-collectors'
    | '/explore'
    | '/group-management'
    | '/my-profile'
    | '/privilege-zones'
    | '/changepassword'
    | '/expired-password'
    | '/login'
    | '/user-disabled'
    | '/administration/bloodhound-configuration'
    | '/administration/data-quality'
    | '/administration/database-management'
    | '/administration/early-access-features'
    | '/administration/file-ingest'
    | '/administration/manage-users'
    | '/administration/opengraph-management'
    | '/administration/sso-configuration'
    | '/privilege-zones/history'
    | '/administration/'
    | '/privilege-zones/'
    | '/privilege-zones/labels/$labelId/details'
    | '/privilege-zones/labels/$labelId/save'
    | '/privilege-zones/zones/$zoneId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/save'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/api-explorer'
    | '/download-collectors'
    | '/explore'
    | '/group-management'
    | '/my-profile'
    | '/changepassword'
    | '/expired-password'
    | '/login'
    | '/user-disabled'
    | '/administration/bloodhound-configuration'
    | '/administration/data-quality'
    | '/administration/database-management'
    | '/administration/early-access-features'
    | '/administration/file-ingest'
    | '/administration/manage-users'
    | '/administration/opengraph-management'
    | '/administration/sso-configuration'
    | '/privilege-zones/history'
    | '/administration'
    | '/privilege-zones'
    | '/privilege-zones/labels/$labelId/details'
    | '/privilege-zones/labels/$labelId/save'
    | '/privilege-zones/zones/$zoneId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/save'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
  id:
    | '__root__'
    | '/$'
    | '/administration'
    | '/api-explorer'
    | '/download-collectors'
    | '/explore'
    | '/group-management'
    | '/my-profile'
    | '/privilege-zones'
    | '/(auth)/changepassword'
    | '/(auth)/expired-password'
    | '/(auth)/login'
    | '/(auth)/user-disabled'
    | '/administration/bloodhound-configuration'
    | '/administration/data-quality'
    | '/administration/database-management'
    | '/administration/early-access-features'
    | '/administration/file-ingest'
    | '/administration/manage-users'
    | '/administration/opengraph-management'
    | '/administration/sso-configuration'
    | '/privilege-zones/history'
    | '/administration/'
    | '/privilege-zones/'
    | '/privilege-zones/labels/$labelId/details'
    | '/privilege-zones/labels/$labelId/save'
    | '/privilege-zones/zones/$zoneId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/save'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/details'
    | '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details'
    | '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AdministrationRoute: typeof AdministrationRouteWithChildren
  ApiExplorerRoute: typeof ApiExplorerRoute
  DownloadCollectorsRoute: typeof DownloadCollectorsRoute
  ExploreRoute: typeof ExploreRoute
  GroupManagementRoute: typeof GroupManagementRoute
  MyProfileRoute: typeof MyProfileRoute
  PrivilegeZonesRoute: typeof PrivilegeZonesRouteWithChildren
  authChangepasswordRoute: typeof authChangepasswordRoute
  authExpiredPasswordRoute: typeof authExpiredPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authUserDisabledRoute: typeof authUserDisabledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privilege-zones': {
      id: '/privilege-zones'
      path: '/privilege-zones'
      fullPath: '/privilege-zones'
      preLoaderRoute: typeof PrivilegeZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-management': {
      id: '/group-management'
      path: '/group-management'
      fullPath: '/group-management'
      preLoaderRoute: typeof GroupManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-collectors': {
      id: '/download-collectors'
      path: '/download-collectors'
      fullPath: '/download-collectors'
      preLoaderRoute: typeof DownloadCollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-explorer': {
      id: '/api-explorer'
      path: '/api-explorer'
      fullPath: '/api-explorer'
      preLoaderRoute: typeof ApiExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privilege-zones/': {
      id: '/privilege-zones/'
      path: '/'
      fullPath: '/privilege-zones/'
      preLoaderRoute: typeof PrivilegeZonesIndexRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/administration/': {
      id: '/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof AdministrationIndexRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/privilege-zones/history': {
      id: '/privilege-zones/history'
      path: '/history'
      fullPath: '/privilege-zones/history'
      preLoaderRoute: typeof PrivilegeZonesHistoryRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/administration/sso-configuration': {
      id: '/administration/sso-configuration'
      path: '/sso-configuration'
      fullPath: '/administration/sso-configuration'
      preLoaderRoute: typeof AdministrationSsoConfigurationRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/opengraph-management': {
      id: '/administration/opengraph-management'
      path: '/opengraph-management'
      fullPath: '/administration/opengraph-management'
      preLoaderRoute: typeof AdministrationOpengraphManagementRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/manage-users': {
      id: '/administration/manage-users'
      path: '/manage-users'
      fullPath: '/administration/manage-users'
      preLoaderRoute: typeof AdministrationManageUsersRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/file-ingest': {
      id: '/administration/file-ingest'
      path: '/file-ingest'
      fullPath: '/administration/file-ingest'
      preLoaderRoute: typeof AdministrationFileIngestRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/early-access-features': {
      id: '/administration/early-access-features'
      path: '/early-access-features'
      fullPath: '/administration/early-access-features'
      preLoaderRoute: typeof AdministrationEarlyAccessFeaturesRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/database-management': {
      id: '/administration/database-management'
      path: '/database-management'
      fullPath: '/administration/database-management'
      preLoaderRoute: typeof AdministrationDatabaseManagementRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/data-quality': {
      id: '/administration/data-quality'
      path: '/data-quality'
      fullPath: '/administration/data-quality'
      preLoaderRoute: typeof AdministrationDataQualityRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/administration/bloodhound-configuration': {
      id: '/administration/bloodhound-configuration'
      path: '/bloodhound-configuration'
      fullPath: '/administration/bloodhound-configuration'
      preLoaderRoute: typeof AdministrationBloodhoundConfigurationRouteImport
      parentRoute: typeof AdministrationRoute
    }
    '/(auth)/user-disabled': {
      id: '/(auth)/user-disabled'
      path: '/user-disabled'
      fullPath: '/user-disabled'
      preLoaderRoute: typeof authUserDisabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/expired-password': {
      id: '/(auth)/expired-password'
      path: '/expired-password'
      fullPath: '/expired-password'
      preLoaderRoute: typeof authExpiredPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/changepassword': {
      id: '/(auth)/changepassword'
      path: '/changepassword'
      fullPath: '/changepassword'
      preLoaderRoute: typeof authChangepasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privilege-zones/zones/$zoneId/details': {
      id: '/privilege-zones/zones/$zoneId/details'
      path: '/zones/$zoneId/details'
      fullPath: '/privilege-zones/zones/$zoneId/details'
      preLoaderRoute: typeof PrivilegeZonesZonesZoneIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/labels/$labelId/save': {
      id: '/privilege-zones/labels/$labelId/save'
      path: '/labels/$labelId/save'
      fullPath: '/privilege-zones/labels/$labelId/save'
      preLoaderRoute: typeof PrivilegeZonesLabelsLabelIdSaveRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/labels/$labelId/details': {
      id: '/privilege-zones/labels/$labelId/details'
      path: '/labels/$labelId/details'
      fullPath: '/privilege-zones/labels/$labelId/details'
      preLoaderRoute: typeof PrivilegeZonesLabelsLabelIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/zones/$zoneId/rules/$ruleId/details': {
      id: '/privilege-zones/zones/$zoneId/rules/$ruleId/details'
      path: '/zones/$zoneId/rules/$ruleId/details'
      fullPath: '/privilege-zones/zones/$zoneId/rules/$ruleId/details'
      preLoaderRoute: typeof PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/labels/$labelId/rules/$ruleId/save': {
      id: '/privilege-zones/labels/$labelId/rules/$ruleId/save'
      path: '/labels/$labelId/rules/$ruleId/save'
      fullPath: '/privilege-zones/labels/$labelId/rules/$ruleId/save'
      preLoaderRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/labels/$labelId/rules/$ruleId/details': {
      id: '/privilege-zones/labels/$labelId/rules/$ruleId/details'
      path: '/labels/$labelId/rules/$ruleId/details'
      fullPath: '/privilege-zones/labels/$labelId/rules/$ruleId/details'
      preLoaderRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details': {
      id: '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
      path: '/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
      fullPath: '/privilege-zones/zones/$zoneId/rules/$ruleId/objects/$objectId/details'
      preLoaderRoute: typeof PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
    '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details': {
      id: '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details'
      path: '/labels/$labelId/rules/$ruleId/objects/$objectId/details'
      fullPath: '/privilege-zones/labels/$labelId/rules/$ruleId/objects/$objectId/details'
      preLoaderRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRouteImport
      parentRoute: typeof PrivilegeZonesRoute
    }
  }
}

interface AdministrationRouteChildren {
  AdministrationBloodhoundConfigurationRoute: typeof AdministrationBloodhoundConfigurationRoute
  AdministrationDataQualityRoute: typeof AdministrationDataQualityRoute
  AdministrationDatabaseManagementRoute: typeof AdministrationDatabaseManagementRoute
  AdministrationEarlyAccessFeaturesRoute: typeof AdministrationEarlyAccessFeaturesRoute
  AdministrationFileIngestRoute: typeof AdministrationFileIngestRoute
  AdministrationManageUsersRoute: typeof AdministrationManageUsersRoute
  AdministrationOpengraphManagementRoute: typeof AdministrationOpengraphManagementRoute
  AdministrationSsoConfigurationRoute: typeof AdministrationSsoConfigurationRoute
  AdministrationIndexRoute: typeof AdministrationIndexRoute
}

const AdministrationRouteChildren: AdministrationRouteChildren = {
  AdministrationBloodhoundConfigurationRoute:
    AdministrationBloodhoundConfigurationRoute,
  AdministrationDataQualityRoute: AdministrationDataQualityRoute,
  AdministrationDatabaseManagementRoute: AdministrationDatabaseManagementRoute,
  AdministrationEarlyAccessFeaturesRoute:
    AdministrationEarlyAccessFeaturesRoute,
  AdministrationFileIngestRoute: AdministrationFileIngestRoute,
  AdministrationManageUsersRoute: AdministrationManageUsersRoute,
  AdministrationOpengraphManagementRoute:
    AdministrationOpengraphManagementRoute,
  AdministrationSsoConfigurationRoute: AdministrationSsoConfigurationRoute,
  AdministrationIndexRoute: AdministrationIndexRoute,
}

const AdministrationRouteWithChildren = AdministrationRoute._addFileChildren(
  AdministrationRouteChildren,
)

interface PrivilegeZonesRouteChildren {
  PrivilegeZonesHistoryRoute: typeof PrivilegeZonesHistoryRoute
  PrivilegeZonesIndexRoute: typeof PrivilegeZonesIndexRoute
  PrivilegeZonesLabelsLabelIdDetailsRoute: typeof PrivilegeZonesLabelsLabelIdDetailsRoute
  PrivilegeZonesLabelsLabelIdSaveRoute: typeof PrivilegeZonesLabelsLabelIdSaveRoute
  PrivilegeZonesZonesZoneIdDetailsRoute: typeof PrivilegeZonesZonesZoneIdDetailsRoute
  PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute
  PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute
  PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute: typeof PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute
  PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute: typeof PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute
  PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute: typeof PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute
}

const PrivilegeZonesRouteChildren: PrivilegeZonesRouteChildren = {
  PrivilegeZonesHistoryRoute: PrivilegeZonesHistoryRoute,
  PrivilegeZonesIndexRoute: PrivilegeZonesIndexRoute,
  PrivilegeZonesLabelsLabelIdDetailsRoute:
    PrivilegeZonesLabelsLabelIdDetailsRoute,
  PrivilegeZonesLabelsLabelIdSaveRoute: PrivilegeZonesLabelsLabelIdSaveRoute,
  PrivilegeZonesZonesZoneIdDetailsRoute: PrivilegeZonesZonesZoneIdDetailsRoute,
  PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute:
    PrivilegeZonesLabelsLabelIdRulesRuleIdDetailsRoute,
  PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute:
    PrivilegeZonesLabelsLabelIdRulesRuleIdSaveRoute,
  PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute:
    PrivilegeZonesZonesZoneIdRulesRuleIdDetailsRoute,
  PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute:
    PrivilegeZonesLabelsLabelIdRulesRuleIdObjectsObjectIdDetailsRoute,
  PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute:
    PrivilegeZonesZonesZoneIdRulesRuleIdObjectsObjectIdDetailsRoute,
}

const PrivilegeZonesRouteWithChildren = PrivilegeZonesRoute._addFileChildren(
  PrivilegeZonesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AdministrationRoute: AdministrationRouteWithChildren,
  ApiExplorerRoute: ApiExplorerRoute,
  DownloadCollectorsRoute: DownloadCollectorsRoute,
  ExploreRoute: ExploreRoute,
  GroupManagementRoute: GroupManagementRoute,
  MyProfileRoute: MyProfileRoute,
  PrivilegeZonesRoute: PrivilegeZonesRouteWithChildren,
  authChangepasswordRoute: authChangepasswordRoute,
  authExpiredPasswordRoute: authExpiredPasswordRoute,
  authLoginRoute: authLoginRoute,
  authUserDisabledRoute: authUserDisabledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
