apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.bloodhound.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  bloodhound.config.json: |
    {
      "version": 1,
      "bind_addr": "0.0.0.0:{{ .Values.bloodhound.service.port }}",
      "metrics_port": ":{{ (index .Values.bloodhound.container.ports 1).containerPort }}",
      "root_url": "http://{{ .Values.bloodhound.ingress.host }}",
      "work_dir": "/opt/bloodhound/work",
      "log_level": "INFO",
      "log_path": "bloodhound.log",
      "features": {
        "enable_auth": true
      },
      "database": {
        "connection": "user={{ .Values.appdb.container.env.POSTGRES_USER }} password={{ .Values.appdb.container.env.POSTGRES_PASSWORD }} dbname={{ .Values.appdb.container.env.POSTGRES_DB }} host={{ .Values.appdb.service.name }}"
      },
      "neo4j": {
        "connection": "neo4j://{{ .Values.graphdb.container.env.NEO4J_AUTH_USER }}:{{ .Values.graphdb.container.env.NEO4J_AUTH_PASS }}@{{ .Values.graphdb.service.name }}:{{ (index .Values.graphdb.service.ports 0).port }}/"
      },
      "collectors_base_path": "/etc/bloodhound/collectors",
      "default_admin": {
        "principal_name": "admin",
        "first_name": "Bloodhound",
        "last_name": "Admin",
        "email_address": "spam@example.com"
      }
    }
