apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bloodhound.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.bloodhound.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.bloodhound.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.bloodhound.appName }}
    spec:
      containers:
      - name: {{ .Values.bloodhound.container.name }}
        image: {{ .Values.bloodhound.container.image }}
        env:
        - name: bhe_disable_cypher_qc
          value: "{{ .Values.bloodhound.container.env.bhe_disable_cypher_qc }}"
        ports:
        - containerPort: {{ (index .Values.bloodhound.container.ports 0).containerPort }}
        {{- if .Values.bloodhound.configMap.enabled }}
        volumeMounts:
        - name: bloodhound-config
          mountPath: /path/to/config  # Update with actual mount path
        {{- end }}
      {{- if .Values.bloodhound.configMap.enabled }}
      volumes:
      - name: bloodhound-config
        configMap:
          name: {{ .Values.bloodhound.configMap.name }}
      {{- end }}
