apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bloodhound.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.bloodhound.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.bloodhound.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.bloodhound.appName }}
    spec:
      initContainers:
      - name: check-db-availability
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - >
          until nc -z graph-db 7687 && nc -z app-db 5432; do
            echo "Waiting for databases to be ready";
            sleep 5;
          done;
      containers:
      - name: {{ .Values.bloodhound.container.name }}
        image: {{ .Values.bloodhound.container.image }}:{{ .Values.bloodhound.container.version }}
        env:
        - name: bhe_disable_cypher_qc
          value: "{{ .Values.bloodhound.container.env.bhe_disable_cypher_qc }}"
        ports:
        - containerPort: {{ (index .Values.bloodhound.container.ports 0).containerPort }}
        {{- if .Values.bloodhound.configMap.enabled }}
        volumeMounts:
        - name: bloodhound-config
          mountPath: /bloodhound.config.json
          subPath: bloodhound.config.json
        {{- end }}
      {{- if .Values.bloodhound.configMap.enabled }}
      volumes:
      - name: bloodhound-config
        configMap:
          name: {{ .Values.bloodhound.configMap.name }}
      {{- end }}
