{{- if .Values.bloodhound.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.bloodhound.name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.bloodhound.ingress.host }}
    http:
      paths:
      - path: {{ .Values.bloodhound.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.bloodhound.name }}-service
            port:
              number: {{ .Values.bloodhound.service.port }}
  {{- if .Values.bloodhound.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.bloodhound.ingress.host }}
    {{- if .Values.bloodhound.tls.customCert }}
    secretName: {{ .Values.bloodhound.tls.certSecret }}
    {{- end }}
  {{- end }}
{{- end }}
