apiVersion: v1
kind: Namespace
metadata:
  name: bloodhound
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5" # ensures this is executed first
    "helm.sh/hook-delete-policy": before-hook-creation
