// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/dawgs/graph"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphDBRequestAdapter creates a new instance of MockGraphDBRequestAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphDBRequestAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphDBRequestAdapter {
	mock := &MockGraphDBRequestAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphDBRequestAdapter is an autogenerated mock type for the GraphDBRequestAdapter type
type MockGraphDBRequestAdapter struct {
	mock.Mock
}

type MockGraphDBRequestAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphDBRequestAdapter) EXPECT() *MockGraphDBRequestAdapter_Expecter {
	return &MockGraphDBRequestAdapter_Expecter{mock: &_m.Mock}
}

// FetchNodesByObjectIDsAndKinds provides a mock function for the type MockGraphDBRequestAdapter
func (_mock *MockGraphDBRequestAdapter) FetchNodesByObjectIDsAndKinds(ctx context.Context, kinds graph.Kinds, objectIDs ...string) (graph.NodeSet, error) {
	var tmpRet mock.Arguments
	if len(objectIDs) > 0 {
		tmpRet = _mock.Called(ctx, kinds, objectIDs)
	} else {
		tmpRet = _mock.Called(ctx, kinds)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FetchNodesByObjectIDsAndKinds")
	}

	var r0 graph.NodeSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.Kinds, ...string) (graph.NodeSet, error)); ok {
		return returnFunc(ctx, kinds, objectIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.Kinds, ...string) graph.NodeSet); ok {
		r0 = returnFunc(ctx, kinds, objectIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.NodeSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, graph.Kinds, ...string) error); ok {
		r1 = returnFunc(ctx, kinds, objectIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchNodesByObjectIDsAndKinds'
type MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call struct {
	*mock.Call
}

// FetchNodesByObjectIDsAndKinds is a helper method to define mock.On call
//   - ctx context.Context
//   - kinds graph.Kinds
//   - objectIDs ...string
func (_e *MockGraphDBRequestAdapter_Expecter) FetchNodesByObjectIDsAndKinds(ctx interface{}, kinds interface{}, objectIDs ...interface{}) *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call {
	return &MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call{Call: _e.mock.On("FetchNodesByObjectIDsAndKinds",
		append([]interface{}{ctx, kinds}, objectIDs...)...)}
}

func (_c *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call) Run(run func(ctx context.Context, kinds graph.Kinds, objectIDs ...string)) *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 graph.Kinds
		if args[1] != nil {
			arg1 = args[1].(graph.Kinds)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call) Return(nodeSet graph.NodeSet, err error) *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call {
	_c.Call.Return(nodeSet, err)
	return _c
}

func (_c *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call) RunAndReturn(run func(ctx context.Context, kinds graph.Kinds, objectIDs ...string) (graph.NodeSet, error)) *MockGraphDBRequestAdapter_FetchNodesByObjectIDsAndKinds_Call {
	_c.Call.Return(run)
	return _c
}
