// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/analysis/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalysis creates a new instance of MockAnalysis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalysis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalysis {
	mock := &MockAnalysis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalysis is an autogenerated mock type for the Analysis type
type MockAnalysis struct {
	mock.Mock
}

type MockAnalysis_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalysis) EXPECT() *MockAnalysis_Expecter {
	return &MockAnalysis_Expecter{mock: &_m.Mock}
}

// CancelAnalysisRequest provides a mock function for the type MockAnalysis
func (_mock *MockAnalysis) CancelAnalysisRequest(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CancelAnalysisRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalysis_CancelAnalysisRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelAnalysisRequest'
type MockAnalysis_CancelAnalysisRequest_Call struct {
	*mock.Call
}

// CancelAnalysisRequest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAnalysis_Expecter) CancelAnalysisRequest(ctx interface{}) *MockAnalysis_CancelAnalysisRequest_Call {
	return &MockAnalysis_CancelAnalysisRequest_Call{Call: _e.mock.On("CancelAnalysisRequest", ctx)}
}

func (_c *MockAnalysis_CancelAnalysisRequest_Call) Run(run func(ctx context.Context)) *MockAnalysis_CancelAnalysisRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAnalysis_CancelAnalysisRequest_Call) Return(err error) *MockAnalysis_CancelAnalysisRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalysis_CancelAnalysisRequest_Call) RunAndReturn(run func(ctx context.Context) error) *MockAnalysis_CancelAnalysisRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRequest provides a mock function for the type MockAnalysis
func (_mock *MockAnalysis) CreateRequest(ctx context.Context, requestedBy string) (services.RequestedAnalysis, bool, error) {
	ret := _mock.Called(ctx, requestedBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 services.RequestedAnalysis
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (services.RequestedAnalysis, bool, error)); ok {
		return returnFunc(ctx, requestedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) services.RequestedAnalysis); ok {
		r0 = returnFunc(ctx, requestedBy)
	} else {
		r0 = ret.Get(0).(services.RequestedAnalysis)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, requestedBy)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, requestedBy)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAnalysis_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type MockAnalysis_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestedBy string
func (_e *MockAnalysis_Expecter) CreateRequest(ctx interface{}, requestedBy interface{}) *MockAnalysis_CreateRequest_Call {
	return &MockAnalysis_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, requestedBy)}
}

func (_c *MockAnalysis_CreateRequest_Call) Run(run func(ctx context.Context, requestedBy string)) *MockAnalysis_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalysis_CreateRequest_Call) Return(requestedAnalysis services.RequestedAnalysis, b bool, err error) *MockAnalysis_CreateRequest_Call {
	_c.Call.Return(requestedAnalysis, b, err)
	return _c
}

func (_c *MockAnalysis_CreateRequest_Call) RunAndReturn(run func(ctx context.Context, requestedBy string) (services.RequestedAnalysis, bool, error)) *MockAnalysis_CreateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function for the type MockAnalysis
func (_mock *MockAnalysis) GetRequest(context1 context.Context) (services.RequestedAnalysis, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 services.RequestedAnalysis
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (services.RequestedAnalysis, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) services.RequestedAnalysis); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(services.RequestedAnalysis)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalysis_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type MockAnalysis_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockAnalysis_Expecter) GetRequest(context1 interface{}) *MockAnalysis_GetRequest_Call {
	return &MockAnalysis_GetRequest_Call{Call: _e.mock.On("GetRequest", context1)}
}

func (_c *MockAnalysis_GetRequest_Call) Run(run func(context1 context.Context)) *MockAnalysis_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAnalysis_GetRequest_Call) Return(requestedAnalysis services.RequestedAnalysis, err error) *MockAnalysis_GetRequest_Call {
	_c.Call.Return(requestedAnalysis, err)
	return _c
}

func (_c *MockAnalysis_GetRequest_Call) RunAndReturn(run func(context1 context.Context) (services.RequestedAnalysis, error)) *MockAnalysis_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}
