// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/assetgroups"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssetGroupsRequestAdapter creates a new instance of MockAssetGroupsRequestAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetGroupsRequestAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetGroupsRequestAdapter {
	mock := &MockAssetGroupsRequestAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetGroupsRequestAdapter is an autogenerated mock type for the AssetGroupsRequestAdapter type
type MockAssetGroupsRequestAdapter struct {
	mock.Mock
}

type MockAssetGroupsRequestAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetGroupsRequestAdapter) EXPECT() *MockAssetGroupsRequestAdapter_Expecter {
	return &MockAssetGroupsRequestAdapter_Expecter{mock: &_m.Mock}
}

// GetTierZeroTag provides a mock function for the type MockAssetGroupsRequestAdapter
func (_mock *MockAssetGroupsRequestAdapter) GetTierZeroTag(ctx context.Context) (assetgroups.AssetGroupTag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTierZeroTag")
	}

	var r0 assetgroups.AssetGroupTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (assetgroups.AssetGroupTag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) assetgroups.AssetGroupTag); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(assetgroups.AssetGroupTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssetGroupsRequestAdapter_GetTierZeroTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTierZeroTag'
type MockAssetGroupsRequestAdapter_GetTierZeroTag_Call struct {
	*mock.Call
}

// GetTierZeroTag is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAssetGroupsRequestAdapter_Expecter) GetTierZeroTag(ctx interface{}) *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call {
	return &MockAssetGroupsRequestAdapter_GetTierZeroTag_Call{Call: _e.mock.On("GetTierZeroTag", ctx)}
}

func (_c *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call) Run(run func(ctx context.Context)) *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call) Return(v assetgroups.AssetGroupTag, err error) *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call) RunAndReturn(run func(ctx context.Context) (assetgroups.AssetGroupTag, error)) *MockAssetGroupsRequestAdapter_GetTierZeroTag_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveTagIDsWithFallback provides a mock function for the type MockAssetGroupsRequestAdapter
func (_mock *MockAssetGroupsRequestAdapter) ResolveTagIDsWithFallback(ctx context.Context, maybeAssetGroupTagID string) ([]int, error) {
	ret := _mock.Called(ctx, maybeAssetGroupTagID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveTagIDsWithFallback")
	}

	var r0 []int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]int, error)); ok {
		return returnFunc(ctx, maybeAssetGroupTagID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []int); ok {
		r0 = returnFunc(ctx, maybeAssetGroupTagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, maybeAssetGroupTagID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveTagIDsWithFallback'
type MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call struct {
	*mock.Call
}

// ResolveTagIDsWithFallback is a helper method to define mock.On call
//   - ctx context.Context
//   - maybeAssetGroupTagID string
func (_e *MockAssetGroupsRequestAdapter_Expecter) ResolveTagIDsWithFallback(ctx interface{}, maybeAssetGroupTagID interface{}) *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call {
	return &MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call{Call: _e.mock.On("ResolveTagIDsWithFallback", ctx, maybeAssetGroupTagID)}
}

func (_c *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call) Run(run func(ctx context.Context, maybeAssetGroupTagID string)) *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call) Return(ints []int, err error) *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call {
	_c.Call.Return(ints, err)
	return _c
}

func (_c *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call) RunAndReturn(run func(ctx context.Context, maybeAssetGroupTagID string) ([]int, error)) *MockAssetGroupsRequestAdapter_ResolveTagIDsWithFallback_Call {
	_c.Call.Return(run)
	return _c
}
