version: '3'

services:
  bh-ui:
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: cmd/ui/package.json
        - action: rebuild
          path: packages/javascript
          ignore:
            - node_modules