// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// GetAnalysisRequest provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetAnalysisRequest(ctx context.Context) (models.RequestedAnalysis, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAnalysisRequest")
	}

	var r0 models.RequestedAnalysis
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (models.RequestedAnalysis, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) models.RequestedAnalysis); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(models.RequestedAnalysis)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetAnalysisRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnalysisRequest'
type MockDatabase_GetAnalysisRequest_Call struct {
	*mock.Call
}

// GetAnalysisRequest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetAnalysisRequest(ctx interface{}) *MockDatabase_GetAnalysisRequest_Call {
	return &MockDatabase_GetAnalysisRequest_Call{Call: _e.mock.On("GetAnalysisRequest", ctx)}
}

func (_c *MockDatabase_GetAnalysisRequest_Call) Run(run func(ctx context.Context)) *MockDatabase_GetAnalysisRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_GetAnalysisRequest_Call) Return(requestedAnalysis models.RequestedAnalysis, err error) *MockDatabase_GetAnalysisRequest_Call {
	_c.Call.Return(requestedAnalysis, err)
	return _c
}

func (_c *MockDatabase_GetAnalysisRequest_Call) RunAndReturn(run func(ctx context.Context) (models.RequestedAnalysis, error)) *MockDatabase_GetAnalysisRequest_Call {
	_c.Call.Return(run)
	return _c
}
