// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/featureflags/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFeatureFlag creates a new instance of MockFeatureFlag. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureFlag(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureFlag {
	mock := &MockFeatureFlag{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureFlag is an autogenerated mock type for the FeatureFlag type
type MockFeatureFlag struct {
	mock.Mock
}

type MockFeatureFlag_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureFlag) EXPECT() *MockFeatureFlag_Expecter {
	return &MockFeatureFlag_Expecter{mock: &_m.Mock}
}

// GetAllFlags provides a mock function for the type MockFeatureFlag
func (_mock *MockFeatureFlag) GetAllFlags(ctx context.Context) ([]services.FeatureFlag, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFlags")
	}

	var r0 []services.FeatureFlag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]services.FeatureFlag, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []services.FeatureFlag); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.FeatureFlag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureFlag_GetAllFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFlags'
type MockFeatureFlag_GetAllFlags_Call struct {
	*mock.Call
}

// GetAllFlags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFeatureFlag_Expecter) GetAllFlags(ctx interface{}) *MockFeatureFlag_GetAllFlags_Call {
	return &MockFeatureFlag_GetAllFlags_Call{Call: _e.mock.On("GetAllFlags", ctx)}
}

func (_c *MockFeatureFlag_GetAllFlags_Call) Run(run func(ctx context.Context)) *MockFeatureFlag_GetAllFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeatureFlag_GetAllFlags_Call) Return(featureFlags []services.FeatureFlag, err error) *MockFeatureFlag_GetAllFlags_Call {
	_c.Call.Return(featureFlags, err)
	return _c
}

func (_c *MockFeatureFlag_GetAllFlags_Call) RunAndReturn(run func(ctx context.Context) ([]services.FeatureFlag, error)) *MockFeatureFlag_GetAllFlags_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type MockFeatureFlag
func (_mock *MockFeatureFlag) IsEnabled(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureFlag_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockFeatureFlag_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFeatureFlag_Expecter) IsEnabled(ctx interface{}, key interface{}) *MockFeatureFlag_IsEnabled_Call {
	return &MockFeatureFlag_IsEnabled_Call{Call: _e.mock.On("IsEnabled", ctx, key)}
}

func (_c *MockFeatureFlag_IsEnabled_Call) Run(run func(ctx context.Context, key string)) *MockFeatureFlag_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeatureFlag_IsEnabled_Call) Return(b bool, err error) *MockFeatureFlag_IsEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFeatureFlag_IsEnabled_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockFeatureFlag_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleFlag provides a mock function for the type MockFeatureFlag
func (_mock *MockFeatureFlag) ToggleFlag(ctx context.Context, id int32, requestedBy string) (services.FeatureFlag, error) {
	ret := _mock.Called(ctx, id, requestedBy)

	if len(ret) == 0 {
		panic("no return value specified for ToggleFlag")
	}

	var r0 services.FeatureFlag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, string) (services.FeatureFlag, error)); ok {
		return returnFunc(ctx, id, requestedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, string) services.FeatureFlag); ok {
		r0 = returnFunc(ctx, id, requestedBy)
	} else {
		r0 = ret.Get(0).(services.FeatureFlag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, string) error); ok {
		r1 = returnFunc(ctx, id, requestedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureFlag_ToggleFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleFlag'
type MockFeatureFlag_ToggleFlag_Call struct {
	*mock.Call
}

// ToggleFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - requestedBy string
func (_e *MockFeatureFlag_Expecter) ToggleFlag(ctx interface{}, id interface{}, requestedBy interface{}) *MockFeatureFlag_ToggleFlag_Call {
	return &MockFeatureFlag_ToggleFlag_Call{Call: _e.mock.On("ToggleFlag", ctx, id, requestedBy)}
}

func (_c *MockFeatureFlag_ToggleFlag_Call) Run(run func(ctx context.Context, id int32, requestedBy string)) *MockFeatureFlag_ToggleFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFeatureFlag_ToggleFlag_Call) Return(featureFlag services.FeatureFlag, err error) *MockFeatureFlag_ToggleFlag_Call {
	_c.Call.Return(featureFlag, err)
	return _c
}

func (_c *MockFeatureFlag_ToggleFlag_Call) RunAndReturn(run func(ctx context.Context, id int32, requestedBy string) (services.FeatureFlag, error)) *MockFeatureFlag_ToggleFlag_Call {
	_c.Call.Return(run)
	return _c
}
