// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/specterops/bloodhound/cmd/api/src/api/v2 (interfaces: OpenGraphSchemaService)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../../LICENSE.header -destination=./mocks/graphschemaextensions.go -package=mocks . OpenGraphSchemaService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v2 "github.com/specterops/bloodhound/cmd/api/src/api/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenGraphSchemaService is a mock of OpenGraphSchemaService interface.
type MockOpenGraphSchemaService struct {
	ctrl     *gomock.Controller
	recorder *MockOpenGraphSchemaServiceMockRecorder
	isgomock struct{}
}

// MockOpenGraphSchemaServiceMockRecorder is the mock recorder for MockOpenGraphSchemaService.
type MockOpenGraphSchemaServiceMockRecorder struct {
	mock *MockOpenGraphSchemaService
}

// NewMockOpenGraphSchemaService creates a new mock instance.
func NewMockOpenGraphSchemaService(ctrl *gomock.Controller) *MockOpenGraphSchemaService {
	mock := &MockOpenGraphSchemaService{ctrl: ctrl}
	mock.recorder = &MockOpenGraphSchemaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenGraphSchemaService) EXPECT() *MockOpenGraphSchemaServiceMockRecorder {
	return m.recorder
}

// UpsertSchemaEnvironmentWithPrincipalKinds mocks base method.
func (m *MockOpenGraphSchemaService) UpsertSchemaEnvironmentWithPrincipalKinds(ctx context.Context, schemaExtensionId int32, environments []v2.Environment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSchemaEnvironmentWithPrincipalKinds", ctx, schemaExtensionId, environments)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSchemaEnvironmentWithPrincipalKinds indicates an expected call of UpsertSchemaEnvironmentWithPrincipalKinds.
func (mr *MockOpenGraphSchemaServiceMockRecorder) UpsertSchemaEnvironmentWithPrincipalKinds(ctx, schemaExtensionId, environments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSchemaEnvironmentWithPrincipalKinds", reflect.TypeOf((*MockOpenGraphSchemaService)(nil).UpsertSchemaEnvironmentWithPrincipalKinds), ctx, schemaExtensionId, environments)
}
