// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockqueryExecer creates a new instance of MockqueryExecer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockqueryExecer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockqueryExecer {
	mock := &MockqueryExecer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockqueryExecer is an autogenerated mock type for the queryExecer type
type MockqueryExecer struct {
	mock.Mock
}

type MockqueryExecer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockqueryExecer) EXPECT() *MockqueryExecer_Expecter {
	return &MockqueryExecer_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockqueryExecer
func (_mock *MockqueryExecer) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockqueryExecer_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockqueryExecer_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *MockqueryExecer_Expecter) Exec(ctx interface{}, sql interface{}, arguments ...interface{}) *MockqueryExecer_Exec_Call {
	return &MockqueryExecer_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, sql}, arguments...)...)}
}

func (_c *MockqueryExecer_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *MockqueryExecer_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockqueryExecer_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *MockqueryExecer_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *MockqueryExecer_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)) *MockqueryExecer_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockqueryExecer
func (_mock *MockqueryExecer) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockqueryExecer_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockqueryExecer_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *MockqueryExecer_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *MockqueryExecer_Query_Call {
	return &MockqueryExecer_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *MockqueryExecer_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *MockqueryExecer_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockqueryExecer_Query_Call) Return(rows pgx.Rows, err error) *MockqueryExecer_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockqueryExecer_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *MockqueryExecer_Query_Call {
	_c.Call.Return(run)
	return _c
}
