-- Copyright 2026 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- +goose Up
CREATE TABLE IF NOT EXISTS data_quality_object_count_runs (
    run_id text PRIMARY KEY,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS data_quality_source_object_counts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind text NOT NULL,
    node_kind text NOT NULL,
    count bigint NOT NULL,
    run_id text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS data_quality_environment_object_counts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind text NOT NULL,
    environment_kind text NOT NULL,
    environment_id text NOT NULL,
    node_kind text NOT NULL,
    count bigint NOT NULL,
    run_id text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_dq_object_count_runs_created_at ON data_quality_object_count_runs USING btree (created_at);

CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_run_id ON data_quality_source_object_counts USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_source_node_kind ON data_quality_source_object_counts USING btree (source_kind, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_created_at ON data_quality_source_object_counts USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dq_source_obj_counts_run_source_node_kind ON data_quality_source_object_counts USING btree (run_id, source_kind, node_kind);

CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_run_id ON data_quality_environment_object_counts USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_source_env_node_kind ON data_quality_environment_object_counts USING btree (source_kind, environment_kind, environment_id, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_source_node_kind ON data_quality_environment_object_counts USING btree (source_kind, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_created_at ON data_quality_environment_object_counts USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dq_env_obj_counts_run_source_env_node_kind ON data_quality_environment_object_counts USING btree (run_id, source_kind, environment_kind, environment_id, node_kind);

-- +goose Down
DROP TABLE IF EXISTS data_quality_environment_object_counts;
DROP TABLE IF EXISTS data_quality_source_object_counts;
DROP TABLE IF EXISTS data_quality_object_count_runs;
