-- Copyright 2026 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- +goose Up
CREATE TABLE IF NOT EXISTS data_quality_object_count_runs (
    run_id text PRIMARY KEY,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS data_quality_source_object_counts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind text NOT NULL,
    node_kind text NOT NULL,
    count bigint NOT NULL,
    run_id text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS data_quality_environment_object_counts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind text NOT NULL,
    environment_kind text NOT NULL,
    environment_id text NOT NULL,
    node_kind text NOT NULL,
    count bigint NOT NULL,
    run_id text NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_dq_object_count_runs_created_at ON data_quality_object_count_runs USING btree (created_at);

CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_run_id ON data_quality_source_object_counts USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_source_node_kind ON data_quality_source_object_counts USING btree (source_kind, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_source_obj_counts_created_at ON data_quality_source_object_counts USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dq_source_obj_counts_run_source_node_kind ON data_quality_source_object_counts USING btree (run_id, source_kind, node_kind);

CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_run_id ON data_quality_environment_object_counts USING btree (run_id);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_source_env_node_kind ON data_quality_environment_object_counts USING btree (source_kind, environment_kind, environment_id, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_source_node_kind ON data_quality_environment_object_counts USING btree (source_kind, node_kind);
CREATE INDEX IF NOT EXISTS idx_dq_env_obj_counts_created_at ON data_quality_environment_object_counts USING btree (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dq_env_obj_counts_run_source_env_node_kind ON data_quality_environment_object_counts USING btree (run_id, source_kind, environment_kind, environment_id, node_kind);

-- +goose StatementBegin
DO $$
BEGIN
    IF to_regclass('data_quality_object_counts') IS NOT NULL THEN
        INSERT INTO data_quality_source_object_counts (source_kind, node_kind, count, run_id, created_at, updated_at)
        SELECT source_kind, node_kind, count, run_id, created_at, updated_at
        FROM data_quality_object_counts
        ON CONFLICT (run_id, source_kind, node_kind) DO NOTHING;
    END IF;
END $$;
-- +goose StatementEnd

INSERT INTO data_quality_source_object_counts (source_kind, node_kind, count, run_id, created_at, updated_at)
SELECT source_kind, node_kind, object_count, run_id, created_at, updated_at
FROM (
    SELECT 'Base' AS source_kind, node_kind, object_count::bigint, run_id, created_at, updated_at
    FROM ad_data_quality_aggregations
    CROSS JOIN LATERAL (VALUES
        ('Domain', domains),
        ('User', users),
        ('Group', groups),
        ('Computer', computers),
        ('OU', ous),
        ('Container', containers),
        ('GPO', gpos),
        ('AIACA', aiacas),
        ('RootCA', rootcas),
        ('EnterpriseCA', enterprisecas),
        ('NTAuthStore', ntauthstores),
        ('CertTemplate', certtemplates),
        ('IssuancePolicy', issuancepolicies)
    ) AS counts(node_kind, object_count)

    UNION ALL

    SELECT 'AZBase' AS source_kind, node_kind, object_count::bigint, run_id, created_at, updated_at
    FROM azure_data_quality_aggregations
    CROSS JOIN LATERAL (VALUES
        ('AZTenant', tenants),
        ('AZUser', users),
        ('AZGroup', groups),
        ('AZApp', apps),
        ('AZServicePrincipal', service_principals),
        ('AZDevice', devices),
        ('AZManagementGroup', management_groups),
        ('AZSubscription', subscriptions),
        ('AZResourceGroup', resource_groups),
        ('AZVM', vms),
        ('AZKeyVault', key_vaults),
        ('AZAutomationAccount', automation_accounts),
        ('AZContainerRegistry', container_registries),
        ('AZFunctionApp', function_apps),
        ('AZLogicApp', logic_apps),
        ('AZManagedCluster', managed_clusters),
        ('AZVMScaleSet', vm_scale_sets),
        ('AZWebApp', web_apps)
    ) AS counts(node_kind, object_count)
) AS migrated_counts
WHERE object_count > 0
ON CONFLICT (run_id, source_kind, node_kind) DO NOTHING;

INSERT INTO data_quality_environment_object_counts (source_kind, environment_kind, environment_id, node_kind, count, run_id, created_at, updated_at)
SELECT source_kind, environment_kind, environment_id, node_kind, object_count, run_id, created_at, updated_at
FROM (
    SELECT 'Base' AS source_kind, 'Domain' AS environment_kind, domain_sid AS environment_id, node_kind, object_count::bigint, run_id, created_at, updated_at
    FROM ad_data_quality_stats
    CROSS JOIN LATERAL (VALUES
        ('Domain', 1::bigint),
        ('User', users),
        ('Group', groups),
        ('Computer', computers),
        ('OU', ous),
        ('Container', containers),
        ('GPO', gpos),
        ('AIACA', aiacas),
        ('RootCA', rootcas),
        ('EnterpriseCA', enterprisecas),
        ('NTAuthStore', ntauthstores),
        ('CertTemplate', certtemplates),
        ('IssuancePolicy', issuancepolicies)
    ) AS counts(node_kind, object_count)

    UNION ALL

    SELECT 'AZBase' AS source_kind, 'AZTenant' AS environment_kind, tenant_id AS environment_id, node_kind, object_count::bigint, run_id, created_at, updated_at
    FROM azure_data_quality_stats
    CROSS JOIN LATERAL (VALUES
        ('AZTenant', 1::bigint),
        ('AZUser', users),
        ('AZGroup', groups),
        ('AZApp', apps),
        ('AZServicePrincipal', service_principals),
        ('AZDevice', devices),
        ('AZManagementGroup', management_groups),
        ('AZSubscription', subscriptions),
        ('AZResourceGroup', resource_groups),
        ('AZVM', vms),
        ('AZKeyVault', key_vaults),
        ('AZAutomationAccount', automation_accounts),
        ('AZContainerRegistry', container_registries),
        ('AZFunctionApp', function_apps),
        ('AZLogicApp', logic_apps),
        ('AZManagedCluster', managed_clusters),
        ('AZVMScaleSet', vm_scale_sets),
        ('AZWebApp', web_apps)
    ) AS counts(node_kind, object_count)
) AS migrated_counts
WHERE object_count > 0
ON CONFLICT (run_id, source_kind, environment_kind, environment_id, node_kind) DO NOTHING;

INSERT INTO data_quality_object_count_runs (run_id, created_at, updated_at)
SELECT run_id, COALESCE(MIN(created_at), NOW()), COALESCE(MAX(updated_at), NOW())
FROM (
    SELECT run_id, created_at, updated_at
    FROM data_quality_source_object_counts

    UNION ALL

    SELECT run_id, created_at, updated_at
    FROM data_quality_environment_object_counts
) AS object_count_runs
WHERE run_id <> ''
GROUP BY run_id
ON CONFLICT (run_id) DO NOTHING;

-- +goose Down
DELETE FROM data_quality_environment_object_counts AS object_counts
USING (
    SELECT 'Base' AS source_kind, 'Domain' AS environment_kind, domain_sid AS environment_id, node_kind, run_id
    FROM ad_data_quality_stats
    CROSS JOIN LATERAL (VALUES
        ('Domain'),
        ('User'),
        ('Group'),
        ('Computer'),
        ('OU'),
        ('Container'),
        ('GPO'),
        ('AIACA'),
        ('RootCA'),
        ('EnterpriseCA'),
        ('NTAuthStore'),
        ('CertTemplate'),
        ('IssuancePolicy')
    ) AS counts(node_kind)

    UNION ALL

    SELECT 'AZBase' AS source_kind, 'AZTenant' AS environment_kind, tenant_id AS environment_id, node_kind, run_id
    FROM azure_data_quality_stats
    CROSS JOIN LATERAL (VALUES
        ('AZTenant'),
        ('AZUser'),
        ('AZGroup'),
        ('AZApp'),
        ('AZServicePrincipal'),
        ('AZDevice'),
        ('AZManagementGroup'),
        ('AZSubscription'),
        ('AZResourceGroup'),
        ('AZVM'),
        ('AZKeyVault'),
        ('AZAutomationAccount'),
        ('AZContainerRegistry'),
        ('AZFunctionApp'),
        ('AZLogicApp'),
        ('AZManagedCluster'),
        ('AZVMScaleSet'),
        ('AZWebApp')
    ) AS counts(node_kind)
) AS migrated_counts
WHERE object_counts.run_id = migrated_counts.run_id
  AND object_counts.source_kind = migrated_counts.source_kind
  AND object_counts.environment_kind = migrated_counts.environment_kind
  AND object_counts.environment_id = migrated_counts.environment_id
  AND object_counts.node_kind = migrated_counts.node_kind;

-- +goose StatementBegin
DO $$
BEGIN
    IF to_regclass('data_quality_object_counts') IS NOT NULL THEN
        DELETE FROM data_quality_source_object_counts AS object_counts
        USING data_quality_object_counts AS legacy_counts
        WHERE object_counts.run_id = legacy_counts.run_id
          AND object_counts.source_kind = legacy_counts.source_kind
          AND object_counts.node_kind = legacy_counts.node_kind;
    END IF;
END $$;
-- +goose StatementEnd

DELETE FROM data_quality_source_object_counts AS object_counts
USING (
    SELECT 'Base' AS source_kind, node_kind, run_id
    FROM ad_data_quality_aggregations
    CROSS JOIN LATERAL (VALUES
        ('Domain'),
        ('User'),
        ('Group'),
        ('Computer'),
        ('OU'),
        ('Container'),
        ('GPO'),
        ('AIACA'),
        ('RootCA'),
        ('EnterpriseCA'),
        ('NTAuthStore'),
        ('CertTemplate'),
        ('IssuancePolicy')
    ) AS counts(node_kind)

    UNION ALL

    SELECT 'AZBase' AS source_kind, node_kind, run_id
    FROM azure_data_quality_aggregations
    CROSS JOIN LATERAL (VALUES
        ('AZTenant'),
        ('AZUser'),
        ('AZGroup'),
        ('AZApp'),
        ('AZServicePrincipal'),
        ('AZDevice'),
        ('AZManagementGroup'),
        ('AZSubscription'),
        ('AZResourceGroup'),
        ('AZVM'),
        ('AZKeyVault'),
        ('AZAutomationAccount'),
        ('AZContainerRegistry'),
        ('AZFunctionApp'),
        ('AZLogicApp'),
        ('AZManagedCluster'),
        ('AZVMScaleSet'),
        ('AZWebApp')
    ) AS counts(node_kind)
) AS migrated_counts
WHERE object_counts.run_id = migrated_counts.run_id
  AND object_counts.source_kind = migrated_counts.source_kind
  AND object_counts.node_kind = migrated_counts.node_kind;

DELETE FROM data_quality_object_count_runs AS runs
WHERE NOT EXISTS (
    SELECT 1
    FROM data_quality_source_object_counts AS source_counts
    WHERE source_counts.run_id = runs.run_id
)
AND NOT EXISTS (
    SELECT 1
    FROM data_quality_environment_object_counts AS environment_counts
    WHERE environment_counts.run_id = runs.run_id
);
