// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/notes/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// CreateAttachment provides a mock function for the type MockDatabase
func (_mock *MockDatabase) CreateAttachment(ctx context.Context, attachment services.Attachment) (services.Attachment, error) {
	ret := _mock.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttachment")
	}

	var r0 services.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Attachment) (services.Attachment, error)); ok {
		return returnFunc(ctx, attachment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Attachment) services.Attachment); ok {
		r0 = returnFunc(ctx, attachment)
	} else {
		r0 = ret.Get(0).(services.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.Attachment) error); ok {
		r1 = returnFunc(ctx, attachment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_CreateAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttachment'
type MockDatabase_CreateAttachment_Call struct {
	*mock.Call
}

// CreateAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - attachment services.Attachment
func (_e *MockDatabase_Expecter) CreateAttachment(ctx interface{}, attachment interface{}) *MockDatabase_CreateAttachment_Call {
	return &MockDatabase_CreateAttachment_Call{Call: _e.mock.On("CreateAttachment", ctx, attachment)}
}

func (_c *MockDatabase_CreateAttachment_Call) Run(run func(ctx context.Context, attachment services.Attachment)) *MockDatabase_CreateAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.Attachment
		if args[1] != nil {
			arg1 = args[1].(services.Attachment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_CreateAttachment_Call) Return(attachment1 services.Attachment, err error) *MockDatabase_CreateAttachment_Call {
	_c.Call.Return(attachment1, err)
	return _c
}

func (_c *MockDatabase_CreateAttachment_Call) RunAndReturn(run func(ctx context.Context, attachment services.Attachment) (services.Attachment, error)) *MockDatabase_CreateAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNote provides a mock function for the type MockDatabase
func (_mock *MockDatabase) CreateNote(ctx context.Context, note services.Note) (services.Note, error) {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 services.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Note) (services.Note, error)); ok {
		return returnFunc(ctx, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Note) services.Note); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Get(0).(services.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.Note) error); ok {
		r1 = returnFunc(ctx, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockDatabase_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - note services.Note
func (_e *MockDatabase_Expecter) CreateNote(ctx interface{}, note interface{}) *MockDatabase_CreateNote_Call {
	return &MockDatabase_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, note)}
}

func (_c *MockDatabase_CreateNote_Call) Run(run func(ctx context.Context, note services.Note)) *MockDatabase_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.Note
		if args[1] != nil {
			arg1 = args[1].(services.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_CreateNote_Call) Return(note1 services.Note, err error) *MockDatabase_CreateNote_Call {
	_c.Call.Return(note1, err)
	return _c
}

func (_c *MockDatabase_CreateNote_Call) RunAndReturn(run func(ctx context.Context, note services.Note) (services.Note, error)) *MockDatabase_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNote provides a mock function for the type MockDatabase
func (_mock *MockDatabase) DeleteNote(ctx context.Context, noteID int64) error {
	ret := _mock.Called(ctx, noteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, noteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabase_DeleteNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNote'
type MockDatabase_DeleteNote_Call struct {
	*mock.Call
}

// DeleteNote is a helper method to define mock.On call
//   - ctx context.Context
//   - noteID int64
func (_e *MockDatabase_Expecter) DeleteNote(ctx interface{}, noteID interface{}) *MockDatabase_DeleteNote_Call {
	return &MockDatabase_DeleteNote_Call{Call: _e.mock.On("DeleteNote", ctx, noteID)}
}

func (_c *MockDatabase_DeleteNote_Call) Run(run func(ctx context.Context, noteID int64)) *MockDatabase_DeleteNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_DeleteNote_Call) Return(err error) *MockDatabase_DeleteNote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabase_DeleteNote_Call) RunAndReturn(run func(ctx context.Context, noteID int64) error) *MockDatabase_DeleteNote_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachment provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetAttachment(ctx context.Context, attachmentID int64) (services.Attachment, error) {
	ret := _mock.Called(ctx, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachment")
	}

	var r0 services.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (services.Attachment, error)); ok {
		return returnFunc(ctx, attachmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) services.Attachment); ok {
		r0 = returnFunc(ctx, attachmentID)
	} else {
		r0 = ret.Get(0).(services.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, attachmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachment'
type MockDatabase_GetAttachment_Call struct {
	*mock.Call
}

// GetAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - attachmentID int64
func (_e *MockDatabase_Expecter) GetAttachment(ctx interface{}, attachmentID interface{}) *MockDatabase_GetAttachment_Call {
	return &MockDatabase_GetAttachment_Call{Call: _e.mock.On("GetAttachment", ctx, attachmentID)}
}

func (_c *MockDatabase_GetAttachment_Call) Run(run func(ctx context.Context, attachmentID int64)) *MockDatabase_GetAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetAttachment_Call) Return(attachment services.Attachment, err error) *MockDatabase_GetAttachment_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockDatabase_GetAttachment_Call) RunAndReturn(run func(ctx context.Context, attachmentID int64) (services.Attachment, error)) *MockDatabase_GetAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachmentByToken provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetAttachmentByToken(ctx context.Context, token string) (services.Attachment, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachmentByToken")
	}

	var r0 services.Attachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (services.Attachment, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) services.Attachment); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(services.Attachment)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetAttachmentByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachmentByToken'
type MockDatabase_GetAttachmentByToken_Call struct {
	*mock.Call
}

// GetAttachmentByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockDatabase_Expecter) GetAttachmentByToken(ctx interface{}, token interface{}) *MockDatabase_GetAttachmentByToken_Call {
	return &MockDatabase_GetAttachmentByToken_Call{Call: _e.mock.On("GetAttachmentByToken", ctx, token)}
}

func (_c *MockDatabase_GetAttachmentByToken_Call) Run(run func(ctx context.Context, token string)) *MockDatabase_GetAttachmentByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetAttachmentByToken_Call) Return(attachment services.Attachment, err error) *MockDatabase_GetAttachmentByToken_Call {
	_c.Call.Return(attachment, err)
	return _c
}

func (_c *MockDatabase_GetAttachmentByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (services.Attachment, error)) *MockDatabase_GetAttachmentByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetNote provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetNote(ctx context.Context, noteID int64) (services.Note, error) {
	ret := _mock.Called(ctx, noteID)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 services.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (services.Note, error)); ok {
		return returnFunc(ctx, noteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) services.Note); ok {
		r0 = returnFunc(ctx, noteID)
	} else {
		r0 = ret.Get(0).(services.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, noteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNote'
type MockDatabase_GetNote_Call struct {
	*mock.Call
}

// GetNote is a helper method to define mock.On call
//   - ctx context.Context
//   - noteID int64
func (_e *MockDatabase_Expecter) GetNote(ctx interface{}, noteID interface{}) *MockDatabase_GetNote_Call {
	return &MockDatabase_GetNote_Call{Call: _e.mock.On("GetNote", ctx, noteID)}
}

func (_c *MockDatabase_GetNote_Call) Run(run func(ctx context.Context, noteID int64)) *MockDatabase_GetNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetNote_Call) Return(note services.Note, err error) *MockDatabase_GetNote_Call {
	_c.Call.Return(note, err)
	return _c
}

func (_c *MockDatabase_GetNote_Call) RunAndReturn(run func(ctx context.Context, noteID int64) (services.Note, error)) *MockDatabase_GetNote_Call {
	_c.Call.Return(run)
	return _c
}

// ListNotes provides a mock function for the type MockDatabase
func (_mock *MockDatabase) ListNotes(ctx context.Context, filter services.NoteFilter) ([]services.Note, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListNotes")
	}

	var r0 []services.Note
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.NoteFilter) ([]services.Note, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.NoteFilter) []services.Note); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.Note)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.NoteFilter) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, services.NoteFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDatabase_ListNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNotes'
type MockDatabase_ListNotes_Call struct {
	*mock.Call
}

// ListNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - filter services.NoteFilter
func (_e *MockDatabase_Expecter) ListNotes(ctx interface{}, filter interface{}) *MockDatabase_ListNotes_Call {
	return &MockDatabase_ListNotes_Call{Call: _e.mock.On("ListNotes", ctx, filter)}
}

func (_c *MockDatabase_ListNotes_Call) Run(run func(ctx context.Context, filter services.NoteFilter)) *MockDatabase_ListNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.NoteFilter
		if args[1] != nil {
			arg1 = args[1].(services.NoteFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_ListNotes_Call) Return(notes []services.Note, n int, err error) *MockDatabase_ListNotes_Call {
	_c.Call.Return(notes, n, err)
	return _c
}

func (_c *MockDatabase_ListNotes_Call) RunAndReturn(run func(ctx context.Context, filter services.NoteFilter) ([]services.Note, int, error)) *MockDatabase_ListNotes_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type MockDatabase
func (_mock *MockDatabase) ListTags(ctx context.Context) ([]services.TagCount, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []services.TagCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]services.TagCount, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []services.TagCount); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.TagCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockDatabase_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) ListTags(ctx interface{}) *MockDatabase_ListTags_Call {
	return &MockDatabase_ListTags_Call{Call: _e.mock.On("ListTags", ctx)}
}

func (_c *MockDatabase_ListTags_Call) Run(run func(ctx context.Context)) *MockDatabase_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabase_ListTags_Call) Return(tagCounts []services.TagCount, err error) *MockDatabase_ListTags_Call {
	_c.Call.Return(tagCounts, err)
	return _c
}

func (_c *MockDatabase_ListTags_Call) RunAndReturn(run func(ctx context.Context) ([]services.TagCount, error)) *MockDatabase_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNote provides a mock function for the type MockDatabase
func (_mock *MockDatabase) UpdateNote(ctx context.Context, note services.Note) (services.Note, error) {
	ret := _mock.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 services.Note
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Note) (services.Note, error)); ok {
		return returnFunc(ctx, note)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Note) services.Note); ok {
		r0 = returnFunc(ctx, note)
	} else {
		r0 = ret.Get(0).(services.Note)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, services.Note) error); ok {
		r1 = returnFunc(ctx, note)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockDatabase_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - note services.Note
func (_e *MockDatabase_Expecter) UpdateNote(ctx interface{}, note interface{}) *MockDatabase_UpdateNote_Call {
	return &MockDatabase_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, note)}
}

func (_c *MockDatabase_UpdateNote_Call) Run(run func(ctx context.Context, note services.Note)) *MockDatabase_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 services.Note
		if args[1] != nil {
			arg1 = args[1].(services.Note)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_UpdateNote_Call) Return(note1 services.Note, err error) *MockDatabase_UpdateNote_Call {
	_c.Call.Return(note1, err)
	return _c
}

func (_c *MockDatabase_UpdateNote_Call) RunAndReturn(run func(ctx context.Context, note services.Note) (services.Note, error)) *MockDatabase_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}
