// Copyright 2025 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/specterops/bloodhound/cmd/api/src/services/opengraphschema (interfaces: OpenGraphSchemaExtensionRepository)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../../LICENSE.header -destination=./mocks/graphschemaextension.go -package=mocks . OpenGraphSchemaExtensionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/specterops/bloodhound/cmd/api/src/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenGraphSchemaExtensionRepository is a mock of OpenGraphSchemaExtensionRepository interface.
type MockOpenGraphSchemaExtensionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOpenGraphSchemaExtensionRepositoryMockRecorder
	isgomock struct{}
}

// MockOpenGraphSchemaExtensionRepositoryMockRecorder is the mock recorder for MockOpenGraphSchemaExtensionRepository.
type MockOpenGraphSchemaExtensionRepositoryMockRecorder struct {
	mock *MockOpenGraphSchemaExtensionRepository
}

// NewMockOpenGraphSchemaExtensionRepository creates a new mock instance.
func NewMockOpenGraphSchemaExtensionRepository(ctrl *gomock.Controller) *MockOpenGraphSchemaExtensionRepository {
	mock := &MockOpenGraphSchemaExtensionRepository{ctrl: ctrl}
	mock.recorder = &MockOpenGraphSchemaExtensionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenGraphSchemaExtensionRepository) EXPECT() *MockOpenGraphSchemaExtensionRepositoryMockRecorder {
	return m.recorder
}

// CreateGraphSchemaExtension mocks base method.
func (m *MockOpenGraphSchemaExtensionRepository) CreateGraphSchemaExtension(ctx context.Context, name, displayName, version string) (model.GraphSchemaExtension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGraphSchemaExtension", ctx, name, displayName, version)
	ret0, _ := ret[0].(model.GraphSchemaExtension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGraphSchemaExtension indicates an expected call of CreateGraphSchemaExtension.
func (mr *MockOpenGraphSchemaExtensionRepositoryMockRecorder) CreateGraphSchemaExtension(ctx, name, displayName, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGraphSchemaExtension", reflect.TypeOf((*MockOpenGraphSchemaExtensionRepository)(nil).CreateGraphSchemaExtension), ctx, name, displayName, version)
}

// DeleteGraphSchemaExtension mocks base method.
func (m *MockOpenGraphSchemaExtensionRepository) DeleteGraphSchemaExtension(ctx context.Context, extensionId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGraphSchemaExtension", ctx, extensionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGraphSchemaExtension indicates an expected call of DeleteGraphSchemaExtension.
func (mr *MockOpenGraphSchemaExtensionRepositoryMockRecorder) DeleteGraphSchemaExtension(ctx, extensionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGraphSchemaExtension", reflect.TypeOf((*MockOpenGraphSchemaExtensionRepository)(nil).DeleteGraphSchemaExtension), ctx, extensionId)
}

// GetGraphSchemaExtensionById mocks base method.
func (m *MockOpenGraphSchemaExtensionRepository) GetGraphSchemaExtensionById(ctx context.Context, extensionId int32) (model.GraphSchemaExtension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraphSchemaExtensionById", ctx, extensionId)
	ret0, _ := ret[0].(model.GraphSchemaExtension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGraphSchemaExtensionById indicates an expected call of GetGraphSchemaExtensionById.
func (mr *MockOpenGraphSchemaExtensionRepositoryMockRecorder) GetGraphSchemaExtensionById(ctx, extensionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraphSchemaExtensionById", reflect.TypeOf((*MockOpenGraphSchemaExtensionRepository)(nil).GetGraphSchemaExtensionById), ctx, extensionId)
}

// GetGraphSchemaExtensions mocks base method.
func (m *MockOpenGraphSchemaExtensionRepository) GetGraphSchemaExtensions(ctx context.Context, extensionFilters model.Filters, sort model.Sort, skip, limit int) (model.GraphSchemaExtensions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraphSchemaExtensions", ctx, extensionFilters, sort, skip, limit)
	ret0, _ := ret[0].(model.GraphSchemaExtensions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGraphSchemaExtensions indicates an expected call of GetGraphSchemaExtensions.
func (mr *MockOpenGraphSchemaExtensionRepositoryMockRecorder) GetGraphSchemaExtensions(ctx, extensionFilters, sort, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraphSchemaExtensions", reflect.TypeOf((*MockOpenGraphSchemaExtensionRepository)(nil).GetGraphSchemaExtensions), ctx, extensionFilters, sort, skip, limit)
}

// UpdateGraphSchemaExtension mocks base method.
func (m *MockOpenGraphSchemaExtensionRepository) UpdateGraphSchemaExtension(ctx context.Context, extension model.GraphSchemaExtension) (model.GraphSchemaExtension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGraphSchemaExtension", ctx, extension)
	ret0, _ := ret[0].(model.GraphSchemaExtension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGraphSchemaExtension indicates an expected call of UpdateGraphSchemaExtension.
func (mr *MockOpenGraphSchemaExtensionRepositoryMockRecorder) UpdateGraphSchemaExtension(ctx, extension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGraphSchemaExtension", reflect.TypeOf((*MockOpenGraphSchemaExtensionRepository)(nil).UpdateGraphSchemaExtension), ctx, extension)
}
