// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/specterops/bloodhound/cmd/api/src/services/opengraphschema (interfaces: GraphDBKindRepository)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../../LICENSE.header -destination=./mocks/graphdbkindrepository.go -package=mocks . GraphDBKindRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGraphDBKindRepository is a mock of GraphDBKindRepository interface.
type MockGraphDBKindRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGraphDBKindRepositoryMockRecorder
	isgomock struct{}
}

// MockGraphDBKindRepositoryMockRecorder is the mock recorder for MockGraphDBKindRepository.
type MockGraphDBKindRepositoryMockRecorder struct {
	mock *MockGraphDBKindRepository
}

// NewMockGraphDBKindRepository creates a new mock instance.
func NewMockGraphDBKindRepository(ctrl *gomock.Controller) *MockGraphDBKindRepository {
	mock := &MockGraphDBKindRepository{ctrl: ctrl}
	mock.recorder = &MockGraphDBKindRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphDBKindRepository) EXPECT() *MockGraphDBKindRepositoryMockRecorder {
	return m.recorder
}

// RefreshKinds mocks base method.
func (m *MockGraphDBKindRepository) RefreshKinds(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshKinds", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshKinds indicates an expected call of RefreshKinds.
func (mr *MockGraphDBKindRepositoryMockRecorder) RefreshKinds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshKinds", reflect.TypeOf((*MockGraphDBKindRepository)(nil).RefreshKinds), ctx)
}
