// Copyright 2025 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/specterops/bloodhound/cmd/api/src/services/opengraphschema (interfaces: OpenGraphSchemaNodeKindRepository)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../../LICENSE.header -destination=./mocks/graphschemanodekindrepository.go -package=mocks . OpenGraphSchemaNodeKindRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/specterops/bloodhound/cmd/api/src/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenGraphSchemaNodeKindRepository is a mock of OpenGraphSchemaNodeKindRepository interface.
type MockOpenGraphSchemaNodeKindRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOpenGraphSchemaNodeKindRepositoryMockRecorder
	isgomock struct{}
}

// MockOpenGraphSchemaNodeKindRepositoryMockRecorder is the mock recorder for MockOpenGraphSchemaNodeKindRepository.
type MockOpenGraphSchemaNodeKindRepositoryMockRecorder struct {
	mock *MockOpenGraphSchemaNodeKindRepository
}

// NewMockOpenGraphSchemaNodeKindRepository creates a new mock instance.
func NewMockOpenGraphSchemaNodeKindRepository(ctrl *gomock.Controller) *MockOpenGraphSchemaNodeKindRepository {
	mock := &MockOpenGraphSchemaNodeKindRepository{ctrl: ctrl}
	mock.recorder = &MockOpenGraphSchemaNodeKindRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenGraphSchemaNodeKindRepository) EXPECT() *MockOpenGraphSchemaNodeKindRepositoryMockRecorder {
	return m.recorder
}

// CreateGraphSchemaNodeKind mocks base method.
func (m *MockOpenGraphSchemaNodeKindRepository) CreateGraphSchemaNodeKind(ctx context.Context, name string, extensionId int32, displayName, description string, isDisplayKind bool, icon, iconColor string) (model.GraphSchemaNodeKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGraphSchemaNodeKind", ctx, name, extensionId, displayName, description, isDisplayKind, icon, iconColor)
	ret0, _ := ret[0].(model.GraphSchemaNodeKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGraphSchemaNodeKind indicates an expected call of CreateGraphSchemaNodeKind.
func (mr *MockOpenGraphSchemaNodeKindRepositoryMockRecorder) CreateGraphSchemaNodeKind(ctx, name, extensionId, displayName, description, isDisplayKind, icon, iconColor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGraphSchemaNodeKind", reflect.TypeOf((*MockOpenGraphSchemaNodeKindRepository)(nil).CreateGraphSchemaNodeKind), ctx, name, extensionId, displayName, description, isDisplayKind, icon, iconColor)
}

// DeleteGraphSchemaNodeKind mocks base method.
func (m *MockOpenGraphSchemaNodeKindRepository) DeleteGraphSchemaNodeKind(ctx context.Context, schemaNodeKindId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGraphSchemaNodeKind", ctx, schemaNodeKindId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGraphSchemaNodeKind indicates an expected call of DeleteGraphSchemaNodeKind.
func (mr *MockOpenGraphSchemaNodeKindRepositoryMockRecorder) DeleteGraphSchemaNodeKind(ctx, schemaNodeKindId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGraphSchemaNodeKind", reflect.TypeOf((*MockOpenGraphSchemaNodeKindRepository)(nil).DeleteGraphSchemaNodeKind), ctx, schemaNodeKindId)
}

// GetGraphSchemaNodeKindById mocks base method.
func (m *MockOpenGraphSchemaNodeKindRepository) GetGraphSchemaNodeKindById(ctx context.Context, schemaNodeKindID int32) (model.GraphSchemaNodeKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraphSchemaNodeKindById", ctx, schemaNodeKindID)
	ret0, _ := ret[0].(model.GraphSchemaNodeKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGraphSchemaNodeKindById indicates an expected call of GetGraphSchemaNodeKindById.
func (mr *MockOpenGraphSchemaNodeKindRepositoryMockRecorder) GetGraphSchemaNodeKindById(ctx, schemaNodeKindID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraphSchemaNodeKindById", reflect.TypeOf((*MockOpenGraphSchemaNodeKindRepository)(nil).GetGraphSchemaNodeKindById), ctx, schemaNodeKindID)
}

// GetGraphSchemaNodeKinds mocks base method.
func (m *MockOpenGraphSchemaNodeKindRepository) GetGraphSchemaNodeKinds(ctx context.Context, nodeKindFilters model.Filters, sort model.Sort, skip, limit int) (model.GraphSchemaNodeKinds, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraphSchemaNodeKinds", ctx, nodeKindFilters, sort, skip, limit)
	ret0, _ := ret[0].(model.GraphSchemaNodeKinds)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGraphSchemaNodeKinds indicates an expected call of GetGraphSchemaNodeKinds.
func (mr *MockOpenGraphSchemaNodeKindRepositoryMockRecorder) GetGraphSchemaNodeKinds(ctx, nodeKindFilters, sort, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraphSchemaNodeKinds", reflect.TypeOf((*MockOpenGraphSchemaNodeKindRepository)(nil).GetGraphSchemaNodeKinds), ctx, nodeKindFilters, sort, skip, limit)
}

// UpdateGraphSchemaNodeKind mocks base method.
func (m *MockOpenGraphSchemaNodeKindRepository) UpdateGraphSchemaNodeKind(ctx context.Context, schemaNodeKind model.GraphSchemaNodeKind) (model.GraphSchemaNodeKind, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGraphSchemaNodeKind", ctx, schemaNodeKind)
	ret0, _ := ret[0].(model.GraphSchemaNodeKind)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGraphSchemaNodeKind indicates an expected call of UpdateGraphSchemaNodeKind.
func (mr *MockOpenGraphSchemaNodeKindRepositoryMockRecorder) UpdateGraphSchemaNodeKind(ctx, schemaNodeKind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGraphSchemaNodeKind", reflect.TypeOf((*MockOpenGraphSchemaNodeKindRepository)(nil).UpdateGraphSchemaNodeKind), ctx, schemaNodeKind)
}
