// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/specterops/bloodhound/cmd/api/src/services/opengraphschema (interfaces: OpenGraphSchemaRepository)
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../../LICENSE.header -destination=./mocks/opengraphschema.go -package=mocks . OpenGraphSchemaRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/specterops/bloodhound/cmd/api/src/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenGraphSchemaRepository is a mock of OpenGraphSchemaRepository interface.
type MockOpenGraphSchemaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOpenGraphSchemaRepositoryMockRecorder
	isgomock struct{}
}

// MockOpenGraphSchemaRepositoryMockRecorder is the mock recorder for MockOpenGraphSchemaRepository.
type MockOpenGraphSchemaRepositoryMockRecorder struct {
	mock *MockOpenGraphSchemaRepository
}

// NewMockOpenGraphSchemaRepository creates a new mock instance.
func NewMockOpenGraphSchemaRepository(ctrl *gomock.Controller) *MockOpenGraphSchemaRepository {
	mock := &MockOpenGraphSchemaRepository{ctrl: ctrl}
	mock.recorder = &MockOpenGraphSchemaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenGraphSchemaRepository) EXPECT() *MockOpenGraphSchemaRepositoryMockRecorder {
	return m.recorder
}

// DeleteGraphSchemaExtension mocks base method.
func (m *MockOpenGraphSchemaRepository) DeleteGraphSchemaExtension(ctx context.Context, extensionID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGraphSchemaExtension", ctx, extensionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGraphSchemaExtension indicates an expected call of DeleteGraphSchemaExtension.
func (mr *MockOpenGraphSchemaRepositoryMockRecorder) DeleteGraphSchemaExtension(ctx, extensionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGraphSchemaExtension", reflect.TypeOf((*MockOpenGraphSchemaRepository)(nil).DeleteGraphSchemaExtension), ctx, extensionID)
}

// GetGraphSchemaExtensions mocks base method.
func (m *MockOpenGraphSchemaRepository) GetGraphSchemaExtensions(ctx context.Context, extensionFilters model.Filters, sort model.Sort, skip, limit int) (model.GraphSchemaExtensions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraphSchemaExtensions", ctx, extensionFilters, sort, skip, limit)
	ret0, _ := ret[0].(model.GraphSchemaExtensions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGraphSchemaExtensions indicates an expected call of GetGraphSchemaExtensions.
func (mr *MockOpenGraphSchemaRepositoryMockRecorder) GetGraphSchemaExtensions(ctx, extensionFilters, sort, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraphSchemaExtensions", reflect.TypeOf((*MockOpenGraphSchemaRepository)(nil).GetGraphSchemaExtensions), ctx, extensionFilters, sort, skip, limit)
}

// UpsertOpenGraphExtension mocks base method.
func (m *MockOpenGraphSchemaRepository) UpsertOpenGraphExtension(ctx context.Context, graphExtensionInput model.GraphExtensionInput) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertOpenGraphExtension", ctx, graphExtensionInput)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertOpenGraphExtension indicates an expected call of UpsertOpenGraphExtension.
func (mr *MockOpenGraphSchemaRepositoryMockRecorder) UpsertOpenGraphExtension(ctx, graphExtensionInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertOpenGraphExtension", reflect.TypeOf((*MockOpenGraphSchemaRepository)(nil).UpsertOpenGraphExtension), ctx, graphExtensionInput)
}
