// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/specterops/bloodhound/server/users"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(r *http.Request) (users.User, bool) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 users.User
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (users.User, bool)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) users.User); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(users.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) bool); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockResolver_Expecter) Resolve(r interface{}) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", r)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(r *http.Request)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(user users.User, b bool) *MockResolver_Resolve_Call {
	_c.Call.Return(user, b)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(r *http.Request) (users.User, bool)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
