// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/graphdb/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphDB creates a new instance of MockGraphDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphDB {
	mock := &MockGraphDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphDB is an autogenerated mock type for the GraphDB type
type MockGraphDB struct {
	mock.Mock
}

type MockGraphDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphDB) EXPECT() *MockGraphDB_Expecter {
	return &MockGraphDB_Expecter{mock: &_m.Mock}
}

// GetNode provides a mock function for the type MockGraphDB
func (_mock *MockGraphDB) GetNode(ctx context.Context, id int64, includeKindInfo bool) (services.Node, error) {
	ret := _mock.Called(ctx, id, includeKindInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 services.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (services.Node, error)); ok {
		return returnFunc(ctx, id, includeKindInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) services.Node); ok {
		r0 = returnFunc(ctx, id, includeKindInfo)
	} else {
		r0 = ret.Get(0).(services.Node)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, id, includeKindInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphDB_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type MockGraphDB_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - includeKindInfo bool
func (_e *MockGraphDB_Expecter) GetNode(ctx interface{}, id interface{}, includeKindInfo interface{}) *MockGraphDB_GetNode_Call {
	return &MockGraphDB_GetNode_Call{Call: _e.mock.On("GetNode", ctx, id, includeKindInfo)}
}

func (_c *MockGraphDB_GetNode_Call) Run(run func(ctx context.Context, id int64, includeKindInfo bool)) *MockGraphDB_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphDB_GetNode_Call) Return(node services.Node, err error) *MockGraphDB_GetNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *MockGraphDB_GetNode_Call) RunAndReturn(run func(ctx context.Context, id int64, includeKindInfo bool) (services.Node, error)) *MockGraphDB_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationship provides a mock function for the type MockGraphDB
func (_mock *MockGraphDB) GetRelationship(ctx context.Context, id int64, includeKindInfo bool) (services.Relationship, error) {
	ret := _mock.Called(ctx, id, includeKindInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationship")
	}

	var r0 services.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (services.Relationship, error)); ok {
		return returnFunc(ctx, id, includeKindInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) services.Relationship); ok {
		r0 = returnFunc(ctx, id, includeKindInfo)
	} else {
		r0 = ret.Get(0).(services.Relationship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, id, includeKindInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphDB_GetRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationship'
type MockGraphDB_GetRelationship_Call struct {
	*mock.Call
}

// GetRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - includeKindInfo bool
func (_e *MockGraphDB_Expecter) GetRelationship(ctx interface{}, id interface{}, includeKindInfo interface{}) *MockGraphDB_GetRelationship_Call {
	return &MockGraphDB_GetRelationship_Call{Call: _e.mock.On("GetRelationship", ctx, id, includeKindInfo)}
}

func (_c *MockGraphDB_GetRelationship_Call) Run(run func(ctx context.Context, id int64, includeKindInfo bool)) *MockGraphDB_GetRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphDB_GetRelationship_Call) Return(relationship services.Relationship, err error) *MockGraphDB_GetRelationship_Call {
	_c.Call.Return(relationship, err)
	return _c
}

func (_c *MockGraphDB_GetRelationship_Call) RunAndReturn(run func(ctx context.Context, id int64, includeKindInfo bool) (services.Relationship, error)) *MockGraphDB_GetRelationship_Call {
	_c.Call.Return(run)
	return _c
}
