# Copyright 2024 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
name: Lint Container Image

description: |
  This composite action performs linting on a specified Dockerfile. Linting helps to enforce best
  practices and eliminate potential issues in Dockerfiles. With the flexibility to recursively
  search for Dockerfiles, this action fosters a more streamlined, error-free build process, thereby
  enhancing the usability and reliability of container images.

inputs:
  dockerfile:
    required: true
    description: |-
      Specifies the name of the Dockerfile to be processed. Providing this input is mandatory.

      Example: Dockerfile
  recursive:
    default: "false"
    description: |-
      Determines whether the search for Dockerfiles should be carried out recursively within
      subdirectories. Providing this input is optional, with the default setting as false.

runs:
  using: composite
  steps:
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ${{ inputs.dockerfile }}
        recursive: ${{ inputs.recursive }}
