// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/cmd/api/src/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalysisRequestSubmitter creates a new instance of MockAnalysisRequestSubmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalysisRequestSubmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalysisRequestSubmitter {
	mock := &MockAnalysisRequestSubmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalysisRequestSubmitter is an autogenerated mock type for the AnalysisRequestSubmitter type
type MockAnalysisRequestSubmitter struct {
	mock.Mock
}

type MockAnalysisRequestSubmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalysisRequestSubmitter) EXPECT() *MockAnalysisRequestSubmitter_Expecter {
	return &MockAnalysisRequestSubmitter_Expecter{mock: &_m.Mock}
}

// SubmitAnalysisRequest provides a mock function for the type MockAnalysisRequestSubmitter
func (_mock *MockAnalysisRequestSubmitter) SubmitAnalysisRequest(ctx context.Context, requestedBy string, analysisMode model.AnalysisMode) error {
	ret := _mock.Called(ctx, requestedBy, analysisMode)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAnalysisRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.AnalysisMode) error); ok {
		r0 = returnFunc(ctx, requestedBy, analysisMode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitAnalysisRequest'
type MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call struct {
	*mock.Call
}

// SubmitAnalysisRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestedBy string
//   - analysisMode model.AnalysisMode
func (_e *MockAnalysisRequestSubmitter_Expecter) SubmitAnalysisRequest(ctx interface{}, requestedBy interface{}, analysisMode interface{}) *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call {
	return &MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call{Call: _e.mock.On("SubmitAnalysisRequest", ctx, requestedBy, analysisMode)}
}

func (_c *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call) Run(run func(ctx context.Context, requestedBy string, analysisMode model.AnalysisMode)) *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.AnalysisMode
		if args[2] != nil {
			arg2 = args[2].(model.AnalysisMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call) Return(err error) *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call) RunAndReturn(run func(ctx context.Context, requestedBy string, analysisMode model.AnalysisMode) error) *MockAnalysisRequestSubmitter_SubmitAnalysisRequest_Call {
	_c.Call.Return(run)
	return _c
}
