// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/specterops/bloodhound/packages/go/params"
	"github.com/specterops/bloodhound/server/identity/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentity creates a new instance of MockIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentity {
	mock := &MockIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentity is an autogenerated mock type for the Identity type
type MockIdentity struct {
	mock.Mock
}

type MockIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentity) EXPECT() *MockIdentity_Expecter {
	return &MockIdentity_Expecter{mock: &_m.Mock}
}

// GetPermission provides a mock function for the type MockIdentity
func (_mock *MockIdentity) GetPermission(ctx context.Context, id int) (services.Permission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermission")
	}

	var r0 services.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (services.Permission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) services.Permission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(services.Permission)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentity_GetPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermission'
type MockIdentity_GetPermission_Call struct {
	*mock.Call
}

// GetPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIdentity_Expecter) GetPermission(ctx interface{}, id interface{}) *MockIdentity_GetPermission_Call {
	return &MockIdentity_GetPermission_Call{Call: _e.mock.On("GetPermission", ctx, id)}
}

func (_c *MockIdentity_GetPermission_Call) Run(run func(ctx context.Context, id int)) *MockIdentity_GetPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentity_GetPermission_Call) Return(permission services.Permission, err error) *MockIdentity_GetPermission_Call {
	_c.Call.Return(permission, err)
	return _c
}

func (_c *MockIdentity_GetPermission_Call) RunAndReturn(run func(ctx context.Context, id int) (services.Permission, error)) *MockIdentity_GetPermission_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type MockIdentity
func (_mock *MockIdentity) GetRole(ctx context.Context, id int32) (services.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 services.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (services.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) services.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(services.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentity_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type MockIdentity_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockIdentity_Expecter) GetRole(ctx interface{}, id interface{}) *MockIdentity_GetRole_Call {
	return &MockIdentity_GetRole_Call{Call: _e.mock.On("GetRole", ctx, id)}
}

func (_c *MockIdentity_GetRole_Call) Run(run func(ctx context.Context, id int32)) *MockIdentity_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentity_GetRole_Call) Return(role services.Role, err error) *MockIdentity_GetRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockIdentity_GetRole_Call) RunAndReturn(run func(ctx context.Context, id int32) (services.Role, error)) *MockIdentity_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPreferences provides a mock function for the type MockIdentity
func (_mock *MockIdentity) GetUserPreferences(ctx context.Context, userID uuid.UUID) ([]byte, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPreferences")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]byte, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []byte); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentity_GetUserPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPreferences'
type MockIdentity_GetUserPreferences_Call struct {
	*mock.Call
}

// GetUserPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockIdentity_Expecter) GetUserPreferences(ctx interface{}, userID interface{}) *MockIdentity_GetUserPreferences_Call {
	return &MockIdentity_GetUserPreferences_Call{Call: _e.mock.On("GetUserPreferences", ctx, userID)}
}

func (_c *MockIdentity_GetUserPreferences_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockIdentity_GetUserPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentity_GetUserPreferences_Call) Return(bytes []byte, err error) *MockIdentity_GetUserPreferences_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIdentity_GetUserPreferences_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]byte, error)) *MockIdentity_GetUserPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// ListPermissions provides a mock function for the type MockIdentity
func (_mock *MockIdentity) ListPermissions(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems) ([]services.Permission, error) {
	ret := _mock.Called(ctx, queryFilters, sortItems)

	if len(ret) == 0 {
		panic("no return value specified for ListPermissions")
	}

	var r0 []services.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.Filters, params.SortItems) ([]services.Permission, error)); ok {
		return returnFunc(ctx, queryFilters, sortItems)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.Filters, params.SortItems) []services.Permission); ok {
		r0 = returnFunc(ctx, queryFilters, sortItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.Permission)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, params.Filters, params.SortItems) error); ok {
		r1 = returnFunc(ctx, queryFilters, sortItems)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentity_ListPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPermissions'
type MockIdentity_ListPermissions_Call struct {
	*mock.Call
}

// ListPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - queryFilters params.Filters
//   - sortItems params.SortItems
func (_e *MockIdentity_Expecter) ListPermissions(ctx interface{}, queryFilters interface{}, sortItems interface{}) *MockIdentity_ListPermissions_Call {
	return &MockIdentity_ListPermissions_Call{Call: _e.mock.On("ListPermissions", ctx, queryFilters, sortItems)}
}

func (_c *MockIdentity_ListPermissions_Call) Run(run func(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems)) *MockIdentity_ListPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 params.Filters
		if args[1] != nil {
			arg1 = args[1].(params.Filters)
		}
		var arg2 params.SortItems
		if args[2] != nil {
			arg2 = args[2].(params.SortItems)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIdentity_ListPermissions_Call) Return(permissions []services.Permission, err error) *MockIdentity_ListPermissions_Call {
	_c.Call.Return(permissions, err)
	return _c
}

func (_c *MockIdentity_ListPermissions_Call) RunAndReturn(run func(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems) ([]services.Permission, error)) *MockIdentity_ListPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function for the type MockIdentity
func (_mock *MockIdentity) ListRoles(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems) ([]services.Role, error) {
	ret := _mock.Called(ctx, queryFilters, sortItems)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 []services.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.Filters, params.SortItems) ([]services.Role, error)); ok {
		return returnFunc(ctx, queryFilters, sortItems)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.Filters, params.SortItems) []services.Role); ok {
		r0 = returnFunc(ctx, queryFilters, sortItems)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, params.Filters, params.SortItems) error); ok {
		r1 = returnFunc(ctx, queryFilters, sortItems)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentity_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type MockIdentity_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - queryFilters params.Filters
//   - sortItems params.SortItems
func (_e *MockIdentity_Expecter) ListRoles(ctx interface{}, queryFilters interface{}, sortItems interface{}) *MockIdentity_ListRoles_Call {
	return &MockIdentity_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx, queryFilters, sortItems)}
}

func (_c *MockIdentity_ListRoles_Call) Run(run func(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems)) *MockIdentity_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 params.Filters
		if args[1] != nil {
			arg1 = args[1].(params.Filters)
		}
		var arg2 params.SortItems
		if args[2] != nil {
			arg2 = args[2].(params.SortItems)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIdentity_ListRoles_Call) Return(roles []services.Role, err error) *MockIdentity_ListRoles_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockIdentity_ListRoles_Call) RunAndReturn(run func(ctx context.Context, queryFilters params.Filters, sortItems params.SortItems) ([]services.Role, error)) *MockIdentity_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUserPreferences provides a mock function for the type MockIdentity
func (_mock *MockIdentity) UpsertUserPreferences(ctx context.Context, userID uuid.UUID, storage []byte) error {
	ret := _mock.Called(ctx, userID, storage)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUserPreferences")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte) error); ok {
		r0 = returnFunc(ctx, userID, storage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentity_UpsertUserPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUserPreferences'
type MockIdentity_UpsertUserPreferences_Call struct {
	*mock.Call
}

// UpsertUserPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - storage []byte
func (_e *MockIdentity_Expecter) UpsertUserPreferences(ctx interface{}, userID interface{}, storage interface{}) *MockIdentity_UpsertUserPreferences_Call {
	return &MockIdentity_UpsertUserPreferences_Call{Call: _e.mock.On("UpsertUserPreferences", ctx, userID, storage)}
}

func (_c *MockIdentity_UpsertUserPreferences_Call) Run(run func(ctx context.Context, userID uuid.UUID, storage []byte)) *MockIdentity_UpsertUserPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIdentity_UpsertUserPreferences_Call) Return(err error) *MockIdentity_UpsertUserPreferences_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentity_UpsertUserPreferences_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, storage []byte) error) *MockIdentity_UpsertUserPreferences_Call {
	_c.Call.Return(run)
	return _c
}
