// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMaintainer creates a new instance of MockMaintainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintainer {
	mock := &MockMaintainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMaintainer is an autogenerated mock type for the Maintainer type
type MockMaintainer struct {
	mock.Mock
}

type MockMaintainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintainer) EXPECT() *MockMaintainer_Expecter {
	return &MockMaintainer_Expecter{mock: &_m.Mock}
}

// CreateNextPartition provides a mock function for the type MockMaintainer
func (_mock *MockMaintainer) CreateNextPartition(ctx context.Context, asOf time.Time) error {
	ret := _mock.Called(ctx, asOf)

	if len(ret) == 0 {
		panic("no return value specified for CreateNextPartition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, asOf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMaintainer_CreateNextPartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNextPartition'
type MockMaintainer_CreateNextPartition_Call struct {
	*mock.Call
}

// CreateNextPartition is a helper method to define mock.On call
//   - ctx context.Context
//   - asOf time.Time
func (_e *MockMaintainer_Expecter) CreateNextPartition(ctx interface{}, asOf interface{}) *MockMaintainer_CreateNextPartition_Call {
	return &MockMaintainer_CreateNextPartition_Call{Call: _e.mock.On("CreateNextPartition", ctx, asOf)}
}

func (_c *MockMaintainer_CreateNextPartition_Call) Run(run func(ctx context.Context, asOf time.Time)) *MockMaintainer_CreateNextPartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaintainer_CreateNextPartition_Call) Return(err error) *MockMaintainer_CreateNextPartition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMaintainer_CreateNextPartition_Call) RunAndReturn(run func(ctx context.Context, asOf time.Time) error) *MockMaintainer_CreateNextPartition_Call {
	_c.Call.Return(run)
	return _c
}

// DropExpiredPartitions provides a mock function for the type MockMaintainer
func (_mock *MockMaintainer) DropExpiredPartitions(ctx context.Context, asOf time.Time, retentionMonths int) error {
	ret := _mock.Called(ctx, asOf, retentionMonths)

	if len(ret) == 0 {
		panic("no return value specified for DropExpiredPartitions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) error); ok {
		r0 = returnFunc(ctx, asOf, retentionMonths)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMaintainer_DropExpiredPartitions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropExpiredPartitions'
type MockMaintainer_DropExpiredPartitions_Call struct {
	*mock.Call
}

// DropExpiredPartitions is a helper method to define mock.On call
//   - ctx context.Context
//   - asOf time.Time
//   - retentionMonths int
func (_e *MockMaintainer_Expecter) DropExpiredPartitions(ctx interface{}, asOf interface{}, retentionMonths interface{}) *MockMaintainer_DropExpiredPartitions_Call {
	return &MockMaintainer_DropExpiredPartitions_Call{Call: _e.mock.On("DropExpiredPartitions", ctx, asOf, retentionMonths)}
}

func (_c *MockMaintainer_DropExpiredPartitions_Call) Run(run func(ctx context.Context, asOf time.Time, retentionMonths int)) *MockMaintainer_DropExpiredPartitions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMaintainer_DropExpiredPartitions_Call) Return(err error) *MockMaintainer_DropExpiredPartitions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMaintainer_DropExpiredPartitions_Call) RunAndReturn(run func(ctx context.Context, asOf time.Time, retentionMonths int) error) *MockMaintainer_DropExpiredPartitions_Call {
	_c.Call.Return(run)
	return _c
}
