-- Copyright 2025 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- Code generated by Cuelang code gen. DO NOT EDIT!
-- Cuelang source: github.com/specterops/bloodhound/-/tree/main/packages/cue/schemas/
DELETE FROM schema_extensions WHERE name = 'AD';

INSERT INTO schema_extensions (name, display_name, version, is_builtin) VALUES ('AD', 'Active Directory', 'v0.0.1', true);

WITH schema_id AS (
	SELECT id FROM schema_extensions WHERE name = 'AD'
)
INSERT INTO schema_node_kinds (schema_extension_id, name, display_name, description, is_display_kind, icon, icon_color) VALUES
	(schema_id, 'Entity', '', '', false, '', ''),
	(schema_id, 'User', '', '', true, 'fa-user', '#17E625'),
	(schema_id, 'Computer', '', '', true, 'fa-desktop', '#E67873'),
	(schema_id, 'Group', '', '', true, 'fa-users', '#DBE617'),
	(schema_id, 'GPO', '', '', true, 'fa-list', '#998EFD'),
	(schema_id, 'OU', '', '', true, 'fa-sitemap', '#FFAA00'),
	(schema_id, 'Container', '', '', true, 'fa-box', '#F79A78'),
	(schema_id, 'Domain', '', '', true, 'fa-globe', '#17E6B9'),
	(schema_id, 'LocalGroup', '', '', false, '', ''),
	(schema_id, 'LocalUser', '', '', false, '', ''),
	(schema_id, 'AIACA', '', '', true, 'fa-arrows-left-right-to-line', '#9769F0'),
	(schema_id, 'RootCA', '', '', true, 'fa-landmark', '#6968E8'),
	(schema_id, 'EnterpriseCA', '', '', true, 'fa-building', '#4696E9'),
	(schema_id, 'NTAuthStore', '', '', true, 'fa-store', '#D575F5'),
	(schema_id, 'CertTemplate', '', '', true, 'fa-id-card', '#B153F3'),
	(schema_id, 'IssuancePolicy', '', '', true, 'fa-clipboard-check', '#99B2DD');

WITH schema_id AS (
	SELECT id FROM schema_extensions WHERE name = 'AD'
)
INSERT INTO schema_edge_kinds (schema_extension_id, name, description, is_traversable) VALUES
	(schema_id, 'Owns', 'Owns', '', true),
	(schema_id, 'GenericAll', 'GenericAll', '', true),
	(schema_id, 'GenericWrite', 'GenericWrite', '', true),
	(schema_id, 'WriteOwner', 'WriteOwner', '', true),
	(schema_id, 'WriteDACL', 'WriteDACL', '', true),
	(schema_id, 'MemberOf', 'MemberOf', '', true),
	(schema_id, 'ForceChangePassword', 'ForceChangePassword', '', true),
	(schema_id, 'AllExtendedRights', 'AllExtendedRights', '', true),
	(schema_id, 'AddMember', 'AddMember', '', true),
	(schema_id, 'HasSession', 'HasSession', '', true),
	(schema_id, 'Contains', 'Contains', '', true),
	(schema_id, 'GPLink', 'GPLink', '', true),
	(schema_id, 'AllowedToDelegate', 'AllowedToDelegate', '', true),
	(schema_id, 'CoerceToTGT', 'CoerceToTGT', '', true),
	(schema_id, 'GetChanges', 'GetChanges', '', false),
	(schema_id, 'GetChangesAll', 'GetChangesAll', '', false),
	(schema_id, 'GetChangesInFilteredSet', 'GetChangesInFilteredSet', '', false),
	(schema_id, 'CrossForestTrust', 'CrossForestTrust', '', false),
	(schema_id, 'SameForestTrust', 'SameForestTrust', '', true),
	(schema_id, 'SpoofSIDHistory', 'SpoofSIDHistory', '', true),
	(schema_id, 'AbuseTGTDelegation', 'AbuseTGTDelegation', '', true),
	(schema_id, 'AllowedToAct', 'AllowedToAct', '', true),
	(schema_id, 'AdminTo', 'AdminTo', '', true),
	(schema_id, 'CanPSRemote', 'CanPSRemote', '', true),
	(schema_id, 'CanRDP', 'CanRDP', '', true),
	(schema_id, 'ExecuteDCOM', 'ExecuteDCOM', '', true),
	(schema_id, 'HasSIDHistory', 'HasSIDHistory', '', true),
	(schema_id, 'AddSelf', 'AddSelf', '', true),
	(schema_id, 'DCSync', 'DCSync', '', true),
	(schema_id, 'ReadLAPSPassword', 'ReadLAPSPassword', '', true),
	(schema_id, 'ReadGMSAPassword', 'ReadGMSAPassword', '', true),
	(schema_id, 'DumpSMSAPassword', 'DumpSMSAPassword', '', true),
	(schema_id, 'SQLAdmin', 'SQLAdmin', '', true),
	(schema_id, 'AddAllowedToAct', 'AddAllowedToAct', '', true),
	(schema_id, 'WriteSPN', 'WriteSPN', '', true),
	(schema_id, 'AddKeyCredentialLink', 'AddKeyCredentialLink', '', true),
	(schema_id, 'LocalToComputer', 'LocalToComputer', '', false),
	(schema_id, 'MemberOfLocalGroup', 'MemberOfLocalGroup', '', false),
	(schema_id, 'RemoteInteractiveLogonRight', 'RemoteInteractiveLogonRight', '', false),
	(schema_id, 'SyncLAPSPassword', 'SyncLAPSPassword', '', true),
	(schema_id, 'WriteAccountRestrictions', 'WriteAccountRestrictions', '', true),
	(schema_id, 'WriteGPLink', 'WriteGPLink', '', true),
	(schema_id, 'RootCAFor', 'RootCAFor', '', false),
	(schema_id, 'DCFor', 'DCFor', '', true),
	(schema_id, 'PublishedTo', 'PublishedTo', '', false),
	(schema_id, 'ManageCertificates', 'ManageCertificates', '', true),
	(schema_id, 'ManageCA', 'ManageCA', '', true),
	(schema_id, 'DelegatedEnrollmentAgent', 'DelegatedEnrollmentAgent', '', false),
	(schema_id, 'Enroll', 'Enroll', '', false),
	(schema_id, 'HostsCAService', 'HostsCAService', '', false),
	(schema_id, 'WritePKIEnrollmentFlag', 'WritePKIEnrollmentFlag', '', false),
	(schema_id, 'WritePKINameFlag', 'WritePKINameFlag', '', false),
	(schema_id, 'NTAuthStoreFor', 'NTAuthStoreFor', '', false),
	(schema_id, 'TrustedForNTAuth', 'TrustedForNTAuth', '', false),
	(schema_id, 'EnterpriseCAFor', 'EnterpriseCAFor', '', false),
	(schema_id, 'IssuedSignedBy', 'IssuedSignedBy', '', false),
	(schema_id, 'GoldenCert', 'GoldenCert', '', true),
	(schema_id, 'EnrollOnBehalfOf', 'EnrollOnBehalfOf', '', false),
	(schema_id, 'OIDGroupLink', 'OIDGroupLink', '', false),
	(schema_id, 'ExtendedByPolicy', 'ExtendedByPolicy', '', false),
	(schema_id, 'ADCSESC1', 'ADCSESC1', '', true),
	(schema_id, 'ADCSESC3', 'ADCSESC3', '', true),
	(schema_id, 'ADCSESC4', 'ADCSESC4', '', true),
	(schema_id, 'ADCSESC6a', 'ADCSESC6a', '', true),
	(schema_id, 'ADCSESC6b', 'ADCSESC6b', '', true),
	(schema_id, 'ADCSESC9a', 'ADCSESC9a', '', true),
	(schema_id, 'ADCSESC9b', 'ADCSESC9b', '', true),
	(schema_id, 'ADCSESC10a', 'ADCSESC10a', '', true),
	(schema_id, 'ADCSESC10b', 'ADCSESC10b', '', true),
	(schema_id, 'ADCSESC13', 'ADCSESC13', '', true),
	(schema_id, 'SyncedToEntraUser', 'SyncedToEntraUser', '', true),
	(schema_id, 'CoerceAndRelayNTLMToSMB', 'CoerceAndRelayNTLMToSMB', '', true),
	(schema_id, 'CoerceAndRelayNTLMToADCS', 'CoerceAndRelayNTLMToADCS', '', true),
	(schema_id, 'WriteOwnerLimitedRights', 'WriteOwnerLimitedRights', '', true),
	(schema_id, 'WriteOwnerRaw', 'WriteOwnerRaw', '', false),
	(schema_id, 'OwnsLimitedRights', 'OwnsLimitedRights', '', true),
	(schema_id, 'OwnsRaw', 'OwnsRaw', '', false),
	(schema_id, 'ClaimSpecialIdentity', 'ClaimSpecialIdentity', '', true),
	(schema_id, 'CoerceAndRelayNTLMToLDAP', 'CoerceAndRelayNTLMToLDAP', '', true),
	(schema_id, 'CoerceAndRelayNTLMToLDAPS', 'CoerceAndRelayNTLMToLDAPS', '', true),
	(schema_id, 'ContainsIdentity', 'ContainsIdentity', '', true),
	(schema_id, 'PropagatesACEsTo', 'PropagatesACEsTo', '', true),
	(schema_id, 'GPOAppliesTo', 'GPOAppliesTo', '', true),
	(schema_id, 'CanApplyGPO', 'CanApplyGPO', '', true),
	(schema_id, 'HasTrustKeys', 'HasTrustKeys', '', true),
	(schema_id, 'ProtectAdminGroups', 'ProtectAdminGroups', '', false);
