-- Copyright 2025 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- Code generated by Cuelang code gen. DO NOT EDIT!
-- Cuelang source: github.com/specterops/bloodhound/-/tree/main/packages/cue/schemas/
DELETE FROM schema_extensions WHERE name = 'AD';

DO $$
DECLARE
	new_extension_id INT;
BEGIN
	INSERT INTO schema_extensions (name, display_name, version, is_builtin) VALUES ('AD', 'Active Directory', 'v0.0.1', true) RETURNING id INTO new_extension_id;

	INSERT INTO schema_node_kinds (schema_extension_id, name, display_name, description, is_display_kind, icon, icon_color) VALUES
		(new_extension_id, 'Base', 'Entity', '', false, '', ''),
		(new_extension_id, 'User', 'User', '', true, 'fa-user', '#17E625'),
		(new_extension_id, 'Computer', 'Computer', '', true, 'fa-desktop', '#E67873'),
		(new_extension_id, 'Group', 'Group', '', true, 'fa-users', '#DBE617'),
		(new_extension_id, 'GPO', 'GPO', '', true, 'fa-list', '#998EFD'),
		(new_extension_id, 'OU', 'OU', '', true, 'fa-sitemap', '#FFAA00'),
		(new_extension_id, 'Container', 'Container', '', true, 'fa-box', '#F79A78'),
		(new_extension_id, 'Domain', 'Domain', '', true, 'fa-globe', '#17E6B9'),
		(new_extension_id, 'ADLocalGroup', 'LocalGroup', '', false, '', ''),
		(new_extension_id, 'ADLocalUser', 'LocalUser', '', false, '', ''),
		(new_extension_id, 'AIACA', 'AIACA', '', true, 'fa-arrows-left-right-to-line', '#9769F0'),
		(new_extension_id, 'RootCA', 'RootCA', '', true, 'fa-landmark', '#6968E8'),
		(new_extension_id, 'EnterpriseCA', 'EnterpriseCA', '', true, 'fa-building', '#4696E9'),
		(new_extension_id, 'NTAuthStore', 'NTAuthStore', '', true, 'fa-store', '#D575F5'),
		(new_extension_id, 'CertTemplate', 'CertTemplate', '', true, 'fa-id-card', '#B153F3'),
		(new_extension_id, 'IssuancePolicy', 'IssuancePolicy', '', true, 'fa-clipboard-check', '#99B2DD');

	INSERT INTO schema_edge_kinds (schema_extension_id, name, description, is_traversable) VALUES
		(new_extension_id, 'Owns', '', true),
		(new_extension_id, 'GenericAll', '', true),
		(new_extension_id, 'GenericWrite', '', true),
		(new_extension_id, 'WriteOwner', '', true),
		(new_extension_id, 'WriteDacl', '', true),
		(new_extension_id, 'MemberOf', '', true),
		(new_extension_id, 'ForceChangePassword', '', true),
		(new_extension_id, 'AllExtendedRights', '', true),
		(new_extension_id, 'AddMember', '', true),
		(new_extension_id, 'HasSession', '', true),
		(new_extension_id, 'Contains', '', true),
		(new_extension_id, 'GPLink', '', true),
		(new_extension_id, 'AllowedToDelegate', '', true),
		(new_extension_id, 'CoerceToTGT', '', true),
		(new_extension_id, 'GetChanges', '', false),
		(new_extension_id, 'GetChangesAll', '', false),
		(new_extension_id, 'GetChangesInFilteredSet', '', false),
		(new_extension_id, 'CrossForestTrust', '', false),
		(new_extension_id, 'SameForestTrust', '', true),
		(new_extension_id, 'SpoofSIDHistory', '', true),
		(new_extension_id, 'AbuseTGTDelegation', '', true),
		(new_extension_id, 'AllowedToAct', '', true),
		(new_extension_id, 'AdminTo', '', true),
		(new_extension_id, 'CanPSRemote', '', true),
		(new_extension_id, 'CanRDP', '', true),
		(new_extension_id, 'ExecuteDCOM', '', true),
		(new_extension_id, 'HasSIDHistory', '', true),
		(new_extension_id, 'AddSelf', '', true),
		(new_extension_id, 'DCSync', '', true),
		(new_extension_id, 'ReadLAPSPassword', '', true),
		(new_extension_id, 'ReadGMSAPassword', '', true),
		(new_extension_id, 'DumpSMSAPassword', '', true),
		(new_extension_id, 'SQLAdmin', '', true),
		(new_extension_id, 'AddAllowedToAct', '', true),
		(new_extension_id, 'WriteSPN', '', true),
		(new_extension_id, 'AddKeyCredentialLink', '', true),
		(new_extension_id, 'LocalToComputer', '', false),
		(new_extension_id, 'MemberOfLocalGroup', '', false),
		(new_extension_id, 'RemoteInteractiveLogonRight', '', false),
		(new_extension_id, 'SyncLAPSPassword', '', true),
		(new_extension_id, 'WriteAccountRestrictions', '', true),
		(new_extension_id, 'WriteGPLink', '', true),
		(new_extension_id, 'RootCAFor', '', false),
		(new_extension_id, 'DCFor', '', true),
		(new_extension_id, 'PublishedTo', '', false),
		(new_extension_id, 'ManageCertificates', '', true),
		(new_extension_id, 'ManageCA', '', true),
		(new_extension_id, 'DelegatedEnrollmentAgent', '', false),
		(new_extension_id, 'Enroll', '', false),
		(new_extension_id, 'HostsCAService', '', false),
		(new_extension_id, 'WritePKIEnrollmentFlag', '', false),
		(new_extension_id, 'WritePKINameFlag', '', false),
		(new_extension_id, 'NTAuthStoreFor', '', false),
		(new_extension_id, 'TrustedForNTAuth', '', false),
		(new_extension_id, 'EnterpriseCAFor', '', false),
		(new_extension_id, 'IssuedSignedBy', '', false),
		(new_extension_id, 'GoldenCert', '', true),
		(new_extension_id, 'EnrollOnBehalfOf', '', false),
		(new_extension_id, 'OIDGroupLink', '', false),
		(new_extension_id, 'ExtendedByPolicy', '', false),
		(new_extension_id, 'ADCSESC1', '', true),
		(new_extension_id, 'ADCSESC3', '', true),
		(new_extension_id, 'ADCSESC4', '', true),
		(new_extension_id, 'ADCSESC6a', '', true),
		(new_extension_id, 'ADCSESC6b', '', true),
		(new_extension_id, 'ADCSESC9a', '', true),
		(new_extension_id, 'ADCSESC9b', '', true),
		(new_extension_id, 'ADCSESC10a', '', true),
		(new_extension_id, 'ADCSESC10b', '', true),
		(new_extension_id, 'ADCSESC13', '', true),
		(new_extension_id, 'SyncedToEntraUser', '', true),
		(new_extension_id, 'CoerceAndRelayNTLMToSMB', '', true),
		(new_extension_id, 'CoerceAndRelayNTLMToADCS', '', true),
		(new_extension_id, 'WriteOwnerLimitedRights', '', true),
		(new_extension_id, 'WriteOwnerRaw', '', false),
		(new_extension_id, 'OwnsLimitedRights', '', true),
		(new_extension_id, 'OwnsRaw', '', false),
		(new_extension_id, 'ClaimSpecialIdentity', '', true),
		(new_extension_id, 'CoerceAndRelayNTLMToLDAP', '', true),
		(new_extension_id, 'CoerceAndRelayNTLMToLDAPS', '', true),
		(new_extension_id, 'ContainsIdentity', '', true),
		(new_extension_id, 'PropagatesACEsTo', '', true),
		(new_extension_id, 'GPOAppliesTo', '', true),
		(new_extension_id, 'CanApplyGPO', '', true),
		(new_extension_id, 'HasTrustKeys', '', true),
		(new_extension_id, 'ProtectAdminGroups', '', false);
END $$;
