-- Copyright 2025 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- Code generated by Cuelang code gen. DO NOT EDIT!
-- Cuelang source: github.com/specterops/bloodhound/-/tree/main/packages/cue/schemas/
DELETE FROM schema_extensions WHERE name = 'AZ';

INSERT INTO schema_extensions (name, display_name, version, is_builtin) VALUES ('AZ', 'Azure', 'v0.0.1', true);

WITH schema_id AS (
	SELECT id FROM schema_extensions WHERE name = 'AZ'
)
INSERT INTO schema_node_kinds (schema_extension_id, name, display_name, description, is_display_kind, icon, icon_color) VALUES
	(schema_id, 'Entity', '', '', false, '', ''),
	(schema_id, 'VMScaleSet', '', '', false, '', ''),
	(schema_id, 'App', '', '', false, '', ''),
	(schema_id, 'Role', '', '', false, '', ''),
	(schema_id, 'Device', '', '', false, '', ''),
	(schema_id, 'FunctionApp', '', '', false, '', ''),
	(schema_id, 'Group', '', '', true, 'fa-users', '#DBE617'),
	(schema_id, 'KeyVault', '', '', false, '', ''),
	(schema_id, 'ManagementGroup', '', '', false, '', ''),
	(schema_id, 'ResourceGroup', '', '', false, '', ''),
	(schema_id, 'ServicePrincipal', '', '', false, '', ''),
	(schema_id, 'Subscription', '', '', false, '', ''),
	(schema_id, 'Tenant', '', '', false, '', ''),
	(schema_id, 'User', '', '', true, 'fa-user', '#17E625'),
	(schema_id, 'VM', '', '', false, '', ''),
	(schema_id, 'ManagedCluster', '', '', false, '', ''),
	(schema_id, 'ContainerRegistry', '', '', false, '', ''),
	(schema_id, 'WebApp', '', '', false, '', ''),
	(schema_id, 'LogicApp', '', '', false, '', ''),
	(schema_id, 'AutomationAccount', '', '', false, '', '');

WITH schema_id AS (
	SELECT id FROM schema_extensions WHERE name = 'AZ'
)
INSERT INTO schema_edge_kinds (schema_extension_id, name, description, is_traversable) VALUES
	(schema_id, 'AvereContributor', 'AvereContributor', '', true),
	(schema_id, 'Contains', 'Contains', '', true),
	(schema_id, 'Contributor', 'Contributor', '', true),
	(schema_id, 'GetCertificates', 'GetCertificates', '', true),
	(schema_id, 'GetKeys', 'GetKeys', '', true),
	(schema_id, 'GetSecrets', 'GetSecrets', '', true),
	(schema_id, 'HasRole', 'HasRole', '', true),
	(schema_id, 'MemberOf', 'MemberOf', '', true),
	(schema_id, 'Owner', 'Owner', '', true),
	(schema_id, 'RunsAs', 'RunsAs', '', true),
	(schema_id, 'VMContributor', 'VMContributor', '', true),
	(schema_id, 'AutomationContributor', 'AutomationContributor', '', true),
	(schema_id, 'KeyVaultContributor', 'KeyVaultContributor', '', true),
	(schema_id, 'VMAdminLogin', 'VMAdminLogin', '', true),
	(schema_id, 'AddMembers', 'AddMembers', '', true),
	(schema_id, 'AddSecret', 'AddSecret', '', true),
	(schema_id, 'ExecuteCommand', 'ExecuteCommand', '', true),
	(schema_id, 'GlobalAdmin', 'GlobalAdmin', '', true),
	(schema_id, 'PrivilegedAuthAdmin', 'PrivilegedAuthAdmin', '', true),
	(schema_id, 'Grant', 'Grant', '', true),
	(schema_id, 'GrantSelf', 'GrantSelf', '', true),
	(schema_id, 'PrivilegedRoleAdmin', 'PrivilegedRoleAdmin', '', true),
	(schema_id, 'ResetPassword', 'ResetPassword', '', true),
	(schema_id, 'UserAccessAdministrator', 'UserAccessAdministrator', '', true),
	(schema_id, 'Owns', 'Owns', '', true),
	(schema_id, 'ScopedTo', 'ScopedTo', '', false),
	(schema_id, 'CloudAppAdmin', 'CloudAppAdmin', '', true),
	(schema_id, 'AppAdmin', 'AppAdmin', '', true),
	(schema_id, 'AddOwner', 'AddOwner', '', true),
	(schema_id, 'ManagedIdentity', 'ManagedIdentity', '', true),
	(schema_id, 'ApplicationReadWriteAll', 'ApplicationReadWriteAll', '', false),
	(schema_id, 'AppRoleAssignmentReadWriteAll', 'AppRoleAssignmentReadWriteAll', '', false),
	(schema_id, 'DirectoryReadWriteAll', 'DirectoryReadWriteAll', '', false),
	(schema_id, 'GroupReadWriteAll', 'GroupReadWriteAll', '', false),
	(schema_id, 'GroupMemberReadWriteAll', 'GroupMemberReadWriteAll', '', false),
	(schema_id, 'RoleManagementReadWriteDirectory', 'RoleManagementReadWriteDirectory', '', false),
	(schema_id, 'ServicePrincipalEndpointReadWriteAll', 'ServicePrincipalEndpointReadWriteAll', '', false),
	(schema_id, 'AKSContributor', 'AKSContributor', '', true),
	(schema_id, 'NodeResourceGroup', 'NodeResourceGroup', '', true),
	(schema_id, 'WebsiteContributor', 'WebsiteContributor', '', true),
	(schema_id, 'LogicAppContributor', 'LogicAppContributor', '', true),
	(schema_id, 'AZMGAddMember', 'AZMGAddMember', '', true),
	(schema_id, 'AZMGAddOwner', 'AZMGAddOwner', '', true),
	(schema_id, 'AZMGAddSecret', 'AZMGAddSecret', '', true),
	(schema_id, 'AZMGGrantAppRoles', 'AZMGGrantAppRoles', '', true),
	(schema_id, 'AZMGGrantRole', 'AZMGGrantRole', '', true),
	(schema_id, 'SyncedToADUser', 'SyncedToADUser', '', true),
	(schema_id, 'AZRoleEligible', 'AZRoleEligible', '', true),
	(schema_id, 'AZRoleApprover', 'AZRoleApprover', '', true);
