-- Copyright 2025 Specter Ops, Inc.
--
-- Licensed under the Apache License, Version 2.0
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- SPDX-License-Identifier: Apache-2.0
-- Code generated by Cuelang code gen. DO NOT EDIT!
-- Cuelang source: github.com/specterops/bloodhound/-/tree/main/packages/cue/schemas/
DELETE FROM schema_extensions WHERE name = 'AZ';

DO $$
DECLARE
	new_extension_id INT;
BEGIN
	INSERT INTO schema_extensions (name, display_name, version, is_builtin) VALUES ('AZ', 'Azure', 'v0.0.1', true) RETURNING id INTO new_extension_id;

	INSERT INTO schema_node_kinds (schema_extension_id, name, display_name, description, is_display_kind, icon, icon_color) VALUES
		(new_extension_id, 'AZBase', 'Entity', '', false, '', ''),
		(new_extension_id, 'AZVMScaleSet', 'VMScaleSet', '', false, '', ''),
		(new_extension_id, 'AZApp', 'App', '', false, '', ''),
		(new_extension_id, 'AZRole', 'Role', '', false, '', ''),
		(new_extension_id, 'AZDevice', 'Device', '', false, '', ''),
		(new_extension_id, 'AZFunctionApp', 'FunctionApp', '', false, '', ''),
		(new_extension_id, 'AZGroup', 'Group', '', true, 'fa-users', '#DBE617'),
		(new_extension_id, 'AZKeyVault', 'KeyVault', '', false, '', ''),
		(new_extension_id, 'AZManagementGroup', 'ManagementGroup', '', false, '', ''),
		(new_extension_id, 'AZResourceGroup', 'ResourceGroup', '', false, '', ''),
		(new_extension_id, 'AZServicePrincipal', 'ServicePrincipal', '', false, '', ''),
		(new_extension_id, 'AZSubscription', 'Subscription', '', false, '', ''),
		(new_extension_id, 'AZTenant', 'Tenant', '', false, '', ''),
		(new_extension_id, 'AZUser', 'User', '', true, 'fa-user', '#17E625'),
		(new_extension_id, 'AZVM', 'VM', '', false, '', ''),
		(new_extension_id, 'AZManagedCluster', 'ManagedCluster', '', false, '', ''),
		(new_extension_id, 'AZContainerRegistry', 'ContainerRegistry', '', false, '', ''),
		(new_extension_id, 'AZWebApp', 'WebApp', '', false, '', ''),
		(new_extension_id, 'AZLogicApp', 'LogicApp', '', false, '', ''),
		(new_extension_id, 'AZAutomationAccount', 'AutomationAccount', '', false, '', '');

	INSERT INTO schema_edge_kinds (schema_extension_id, name, description, is_traversable) VALUES
		(new_extension_id, 'AZAvereContributor', '', true),
		(new_extension_id, 'AZContains', '', true),
		(new_extension_id, 'AZContributor', '', true),
		(new_extension_id, 'AZGetCertificates', '', true),
		(new_extension_id, 'AZGetKeys', '', true),
		(new_extension_id, 'AZGetSecrets', '', true),
		(new_extension_id, 'AZHasRole', '', true),
		(new_extension_id, 'AZMemberOf', '', true),
		(new_extension_id, 'AZOwner', '', true),
		(new_extension_id, 'AZRunsAs', '', true),
		(new_extension_id, 'AZVMContributor', '', true),
		(new_extension_id, 'AZAutomationContributor', '', true),
		(new_extension_id, 'AZKeyVaultContributor', '', true),
		(new_extension_id, 'AZVMAdminLogin', '', true),
		(new_extension_id, 'AZAddMembers', '', true),
		(new_extension_id, 'AZAddSecret', '', true),
		(new_extension_id, 'AZExecuteCommand', '', true),
		(new_extension_id, 'AZGlobalAdmin', '', true),
		(new_extension_id, 'AZPrivilegedAuthAdmin', '', true),
		(new_extension_id, 'AZGrant', '', true),
		(new_extension_id, 'AZGrantSelf', '', true),
		(new_extension_id, 'AZPrivilegedRoleAdmin', '', true),
		(new_extension_id, 'AZResetPassword', '', true),
		(new_extension_id, 'AZUserAccessAdministrator', '', true),
		(new_extension_id, 'AZOwns', '', true),
		(new_extension_id, 'AZScopedTo', '', false),
		(new_extension_id, 'AZCloudAppAdmin', '', true),
		(new_extension_id, 'AZAppAdmin', '', true),
		(new_extension_id, 'AZAddOwner', '', true),
		(new_extension_id, 'AZManagedIdentity', '', true),
		(new_extension_id, 'AZMGApplication_ReadWrite_All', '', false),
		(new_extension_id, 'AZMGAppRoleAssignment_ReadWrite_All', '', false),
		(new_extension_id, 'AZMGDirectory_ReadWrite_All', '', false),
		(new_extension_id, 'AZMGGroup_ReadWrite_All', '', false),
		(new_extension_id, 'AZMGGroupMember_ReadWrite_All', '', false),
		(new_extension_id, 'AZMGRoleManagement_ReadWrite_Directory', '', false),
		(new_extension_id, 'AZMGServicePrincipalEndpoint_ReadWrite_All', '', false),
		(new_extension_id, 'AZAKSContributor', '', true),
		(new_extension_id, 'AZNodeResourceGroup', '', true),
		(new_extension_id, 'AZWebsiteContributor', '', true),
		(new_extension_id, 'AZLogicAppContributor', '', true),
		(new_extension_id, 'AZMGAddMember', '', true),
		(new_extension_id, 'AZMGAddOwner', '', true),
		(new_extension_id, 'AZMGAddSecret', '', true),
		(new_extension_id, 'AZMGGrantAppRoles', '', true),
		(new_extension_id, 'AZMGGrantRole', '', true),
		(new_extension_id, 'SyncedToADUser', '', true),
		(new_extension_id, 'AZRoleEligible', '', true),
		(new_extension_id, 'AZRoleApprover', '', true);
END $$;
