# Copyright 2024 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

parameters:
  - $ref: './../parameters/header.prefer.yaml'
  - name: environment_id
    description: Environment ID
    in: path
    required: true
    schema:
      type: string
get:
  operationId: FindingTrendsForEnvironment
  summary: List finding trends
  description: Lists findings and their changes in between two dates for an environment
  tags:
    - Attack Paths
    - Enterprise
  parameters:
    # - name: sort_by
    #   description: Sortable columns are composite_risk, start_count, end_count, change.
    #   in: query
    #   schema:
    #     $ref: './../schemas/api.params.query.sort-by.yaml'
    - name: start
      description: Beginning datetime of range (inclusive) in RFC-3339 format; Defaults
        to current datetime minus 30 days
      in: query
      schema:
        type: string
        format: date-time
    - name: end
      description: Ending datetime of range (exclusive) in RFC-3339 format; Defaults
        to current datetime
      in: query
      schema:
        type: string
        format: date-time
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: './../schemas/api.response.time-window.yaml'
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      findings:
                        type: array
                        items:
                          type: object
                          properties:
                            environment_id:
                              type: string
                            finding:
                              type: string
                            composite_risk:
                              type: number
                              format: double
                            finding_count_start:
                              type: integer
                            finding_count_end:
                              type: integer
                      total_finding_count_start:
                        type: integer
                      total_finding_count_end:
                        type: integer

    400:
      $ref: './../responses/bad-request.yaml'
    401:
      $ref: './../responses/unauthorized.yaml'
    403:
      $ref: './../responses/forbidden.yaml'
    404:
      $ref: './../responses/not-found.yaml'
    429:
      $ref: './../responses/too-many-requests.yaml'
    500:
      $ref: './../responses/internal-server-error.yaml'
