# Copyright 2026 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

parameters:
  - $ref: './../parameters/header.prefer.yaml'
get:
  operationId: GetDataQualityEnvironmentObjectCounts
  summary: Get data quality environment object counts
  description: Time series list of object counts grouped by source kind, environment kind, environment ID, and node kind.
  tags:
    - Data Quality
    - Community
    - Enterprise
  parameters:
    - name: source_kind
      description: Filter by source kind.
      in: query
      schema:
        type: string
    - name: environment_kind
      description: Filter by environment kind.
      in: query
      schema:
        type: string
    - name: environment_id
      description: Filter by environment ID.
      in: query
      schema:
        type: string
    - name: node_kind
      description: Filter by node kind.
      in: query
      schema:
        type: string
    - name: run_id
      description: Filter by collection run ID.
      in: query
      schema:
        type: string
        format: uuid
    - name: latest
      description: Return rows for the latest object count run in the selected time range. Cannot be combined with run_id.
      in: query
      allowEmptyValue: true
      schema:
        type: boolean
    - name: sort_by
      description: Sortable columns are source_kind, environment_kind, environment_id, node_kind, count, run_id, created_at, updated_at.
      in: query
      schema:
        $ref: './../schemas/api.params.query.sort-by.yaml'
    - name: start
      description: Beginning datetime of range (inclusive) in RFC-3339 format; Defaults
        to current datetime minus 30 days
      in: query
      schema:
        type: string
        format: date-time
    - name: end
      description: Ending datetime of range (exclusive) in RFC-3339 format; Defaults
        to current datetime
      in: query
      schema:
        type: string
        format: date-time
    - $ref: './../parameters/query.skip.yaml'
    - $ref: './../parameters/query.limit.yaml'
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: './../schemas/api.response.pagination.yaml'
              - $ref: './../schemas/api.response.time-window.yaml'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: './../schemas/model.data-quality-environment-object-count.yaml'
    400:
      $ref: './../responses/bad-request.yaml'
    401:
      $ref: './../responses/unauthorized.yaml'
    403:
      $ref: './../responses/forbidden.yaml'
    429:
      $ref: './../responses/too-many-requests.yaml'
    500:
      $ref: './../responses/internal-server-error.yaml'
