// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/identity/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// GetPermission provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetPermission(ctx context.Context, id int) (services.Permission, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermission")
	}

	var r0 services.Permission
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (services.Permission, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) services.Permission); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(services.Permission)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermission'
type MockDatabase_GetPermission_Call struct {
	*mock.Call
}

// GetPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDatabase_Expecter) GetPermission(ctx interface{}, id interface{}) *MockDatabase_GetPermission_Call {
	return &MockDatabase_GetPermission_Call{Call: _e.mock.On("GetPermission", ctx, id)}
}

func (_c *MockDatabase_GetPermission_Call) Run(run func(ctx context.Context, id int)) *MockDatabase_GetPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetPermission_Call) Return(permission services.Permission, err error) *MockDatabase_GetPermission_Call {
	_c.Call.Return(permission, err)
	return _c
}

func (_c *MockDatabase_GetPermission_Call) RunAndReturn(run func(ctx context.Context, id int) (services.Permission, error)) *MockDatabase_GetPermission_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function for the type MockDatabase
func (_mock *MockDatabase) GetRole(ctx context.Context, id int32) (services.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 services.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (services.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) services.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(services.Role)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabase_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type MockDatabase_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockDatabase_Expecter) GetRole(ctx interface{}, id interface{}) *MockDatabase_GetRole_Call {
	return &MockDatabase_GetRole_Call{Call: _e.mock.On("GetRole", ctx, id)}
}

func (_c *MockDatabase_GetRole_Call) Run(run func(ctx context.Context, id int32)) *MockDatabase_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabase_GetRole_Call) Return(role services.Role, err error) *MockDatabase_GetRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockDatabase_GetRole_Call) RunAndReturn(run func(ctx context.Context, id int32) (services.Role, error)) *MockDatabase_GetRole_Call {
	_c.Call.Return(run)
	return _c
}
