namespace: bloodhoundad

appdb:
  name: bloodhound-postgres
  replicas: 1
  appName: bloodhound-postgres
  container:
    name: postgres
    image: docker.io/library/postgres:13.2
    env:
      POSTGRES_USER: "bloodhound"
      POSTGRES_PASSWORD: "bloodhoundcommunityedition"
      POSTGRES_DB: "bloodhound"
    ports:
      containerPort: 5432
  livenessProbe:
    user: bloodhound
    database: bloodhound
    port: "5432"
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  service:
    enabled: true
    type: ClusterIP
    port: 5432
    targetPort: 5432
  volumes:
    pvcEnabled: false 
    persistentVolumeClaim:
      claimName: bloodhound-postgres-pvc
      size: "1Gi"  # Configurable storage size

graphdb:
  name: graphdb
  replicas: 1
  appName: graphdb
  container:
    name: neo4j
    image: docker.io/library/neo4j:4.4
    env:
      NEO4J_AUTH: "neo4j/bloodhoundcommunityedition"
      NEO4J_dbms_allow__upgrade: "true"
    ports:
      - containerPort: 7687
      - containerPort: 7474
  service:
    enabled: true
    type: ClusterIP
    ports:
      - name: graphdb
        protocol: TCP
        port: 7687
        targetPort: 7687
      - name: http
        protocol: TCP
        port: 7474
        targetPort: 7474
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  volumes:
    pvcEnabled: false 
    persistentVolumeClaim:
      claimName: graphdb-neo4j-data-pvc
      size: "1Gi"  # Configurable storage size

bloodhound:
  name: bloodhound
  replicas: 1
  appName: bloodhound
  container:
    name: bloodhound
    image: docker.io/specterops/bloodhound:latest
    env:
      bhe_disable_cypher_qc: "false"
    ports:
      - containerPort: 8080
  service:
    enabled: true
    type: ClusterIP
    port: 8080
    targetPort: 8080
  ingress:
    enabled: true
    host: bloodhound.example.com
    path: /
    tls: false
  configMap:
    enabled: false
    name: bloodhound-config
