// Copyright 2026 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/specterops/bloodhound/server/graphdb/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeAccessChecker creates a new instance of MockNodeAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeAccessChecker {
	mock := &MockNodeAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeAccessChecker is an autogenerated mock type for the NodeAccessChecker type.
type MockNodeAccessChecker struct {
	mock.Mock
}

type MockNodeAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeAccessChecker) EXPECT() *MockNodeAccessChecker_Expecter {
	return &MockNodeAccessChecker_Expecter{mock: &_m.Mock}
}

// CanAccessNode provides a mock function for the type MockNodeAccessChecker.
func (_mock *MockNodeAccessChecker) CanAccessNode(ctx context.Context, node services.Node) bool {
	ret := _mock.Called(ctx, node)

	if len(ret) == 0 {
		panic("no return value specified for CanAccessNode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, services.Node) bool); ok {
		r0 = returnFunc(ctx, node)
	} else {
		r0 = ret.Bool(0)
	}
	return r0
}

// CanAccessNode sets up expectations for the CanAccessNode method.
func (_e *MockNodeAccessChecker_Expecter) CanAccessNode(ctx any, node any) *mock.Call {
	return _e.mock.On("CanAccessNode", ctx, node)
}
