// Copyright 2025 Specter Ops, Inc.
//
// Licensed under the Apache License, Version 2.0
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
export default {
    data: {
        '12': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'CERTMAN@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'CERTMAN@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2201',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'certman',
                distinguishedname: 'CN=CERTMAN,OU=USERS,OU=TIER0,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1695966948,
                lastlogontimestamp: 1695966443,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1695966321,
                pwdneverexpires: true,
                samaccountname: 'certman',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1695941121,
            },
        },
        '112': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'JD@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'JD@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2113',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'Johnny Döner',
                distinguishedname: 'CN=JOHNNY DÖNER,OU=USERS,OU=TIER0,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1709665027,
                lastlogontimestamp: 1709541513,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1665158089,
                pwdneverexpires: true,
                samaccountname: 'jd',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1665132889,
            },
        },
        '145': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'ALICE@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'ALICE@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2173',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'alice',
                distinguishedname: 'CN=ALICE,OU=USERS,OU=TIER1,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 0,
                lastlogontimestamp: -1,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1681286877,
                pwdneverexpires: true,
                samaccountname: 'alice',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1681261677,
            },
        },
        '146': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'CERTEXT@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'CERTEXT@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2210',
                isTierZero: false,
                admincount: true,
                description: null,
                displayname: 'certext',
                distinguishedname: 'CN=CERTEXT,OU=USERS,OU=TIER1,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1706542139,
                lastlogontimestamp: 1706542085,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1706541813,
                pwdneverexpires: true,
                samaccountname: 'certext',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1706513013,
            },
        },
        '182': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'T1_TONYMONTANA@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'T1_TONYMONTANA@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2110',
                isTierZero: false,
                admincount: true,
                description: null,
                displayname: 'T1_TonyMontana',
                distinguishedname: 'CN=T1_TONYMONTANA,OU=USERS,OU=TIER1,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1674216447,
                lastlogontimestamp: 1673626093,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1664381451,
                pwdneverexpires: true,
                samaccountname: 'T1_TonyMontana',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1664356251,
            },
        },
        '194': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'SVC_DOMAINJOIN@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'SVC_DOMAINJOIN@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2181',
                isTierZero: false,
                admincount: false,
                description: null,
                displayname: 'svc_domainjoin',
                distinguishedname: 'CN=SVC_DOMAINJOIN,OU=USERS,OU=TIER1,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: false,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 0,
                lastlogontimestamp: -1,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1681385806,
                pwdneverexpires: true,
                samaccountname: 'svc_domainjoin',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1681360606,
            },
        },
        '200': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'ROSHI@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'ROSHI@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2194',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'Roshi',
                distinguishedname: 'CN=ROSHI,OU=USERS,OU=TIER0,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1708677450,
                lastlogontimestamp: 1708414903,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1707055837,
                pwdneverexpires: true,
                samaccountname: 'Roshi',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1690420899,
            },
        },
        '201': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'ANDY@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'ANDY@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2187',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'andy',
                distinguishedname: 'CN=ANDY,OU=USERS,OU=TIER1,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 1685544338,
                lastlogontimestamp: 1685544338,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1685544294,
                pwdneverexpires: true,
                samaccountname: 'andy',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1685519094,
            },
        },
        '203': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'FABIAN@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'FABIAN@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-2191',
                isTierZero: true,
                admincount: true,
                description: null,
                displayname: 'Fabian',
                distinguishedname: 'CN=FABIAN,OU=USERS,OU=TIER0,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: true,
                hasspn: false,
                homedirectory: null,
                isaclprotected: true,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 0,
                lastlogontimestamp: -1,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'S-1-5-21-2697957641-2271029196-387917394-512',
                passwordnotreqd: false,
                pwdlastset: 1685613344,
                pwdneverexpires: true,
                samaccountname: 'Fabian',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                system_tags: 'admin_tier_0',
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1685588144,
            },
        },
        '213': {
            color: '#17E625',
            border: {
                color: 'black',
            },
            fontIcon: {
                text: 'fa-user',
            },
            size: 2,
            label: {
                backgroundColor: 'rgba(255,255,255,0.9)',
                fontSize: 2,
                center: false,
                text: 'GUEST@PHANTOM.CORP',
            },
            data: {
                nodetype: 'User',
                name: 'GUEST@PHANTOM.CORP',
                objectid: 'S-1-5-21-2697957641-2271029196-387917394-501',
                isTierZero: false,
                admincount: false,
                description: 'Built-in account for guest access to the computer/domain',
                displayname: 'user name',
                distinguishedname: 'CN=GUEST,CN=USERS,DC=PHANTOM,DC=CORP',
                domain: 'PHANTOM.CORP',
                domainsid: 'S-1-5-21-2697957641-2271029196-387917394',
                dontreqpreauth: false,
                email: null,
                enabled: false,
                hasspn: false,
                homedirectory: null,
                isaclprotected: false,
                lastcollected: '2025-07-08T23:56:24.347104217Z',
                lastlogon: 0,
                lastlogontimestamp: -1,
                lastseen: '2025-07-08T23:56:24.347104217Z',
                logonscript: null,
                ownersid: 'PHANTOM.CORP-S-1-5-32-544',
                passwordnotreqd: true,
                pwdlastset: 0,
                pwdneverexpires: true,
                samaccountname: 'Guest',
                sensitive: false,
                serviceprincipalnames: [],
                sfupassword: null,
                sidhistory: [],
                title: null,
                trustedtoauth: false,
                unconstraineddelegation: false,
                unicodepassword: null,
                unixpassword: null,
                userpassword: null,
                whencreated: 1653361617,
            },
        },
    },
    selectedNode: null,
    open: true,
    allColumnKeys: [
        'nodetype',
        'isTierZero',
        'admincount',
        'description',
        'displayname',
        'distinguishedname',
        'domain',
        'domainsid',
        'dontreqpreauth',
        'email',
        'enabled',
        'gmsa',
        'hasspn',
        'homedirectory',
        'isaclprotected',
        'lastcollected',
        'lastlogon',
        'lastlogontimestamp',
        'lastseen',
        'logonscript',
        'msa',
        'name',
        'objectid',
        'ownersid',
        'passwordnotreqd',
        'pwdlastset',
        'pwdneverexpires',
        'samaccountname',
        'sensitive',
        'serviceprincipalnames',
        'sfupassword',
        'sidhistory',
        'system_tags',
        'title',
        'trustedtoauth',
        'unconstraineddelegation',
        'unicodepassword',
        'unixpassword',
        'userpassword',
        'whencreated',
    ],
    selectedColumns: {
        nodetype: true,
        objectid: true,
        displayname: true,
    },
};
