---
# Copyright 2025 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
name: Build Application

on:
  pull_request:
    branches:
      - main
      - 'stage/**'
    types:
      - opened
      - synchronize

jobs:
  build-application:
    name: Build BloodHound Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    env:
      SB_VERSION: v0.0.0-pr

    steps:
      - name: Checkout source code for this repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # ratchet:actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          check-latest: true

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ratchet:actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: |
          corepack enable
          corepack install
          yarn --version

      - name: Run stbernard deps
        run: |
          go tool stbernard deps

      - name: Run stbernard build
        run: |
          go tool stbernard build
