# Copyright 2024 Specter Ops, Inc.
#
# Licensed under the Apache License, Version 2.0
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Vulnerability Scan

on:
  workflow_call:
    inputs:
      scan_type:
        type: string
        description: |-
          Scan type to use for scanning vulnerability.

          Defaults to 'repo'
        default: repo
      scan_ref:
        type: string
        description: |-
          The direcotry or path in which the scan will be referenced from.

          Default: './'
        default: ./
      severity:
        type: string
        description: |-
          Severities of vulnerabilities to be displayed.

          Default: 'CRITICAL,HIGH'
        default: CRITICAL,HIGH
      exit_code:
        type: string
        description: |-
          The exit code provided when vulnerabilities are found.

          Default: '1'
        default: '1'
      ignore_unfixed:
        type: boolean
        description: |-
          Ignore found unfixed vulnerabilities.

          Default: false
        default: false
      trivy_db_repository:
        type: string
        default: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
      trivy_java_db_repository:
        type: string
        default: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code for this repository
        uses: actions/checkout@v3

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: ${{ inputs.scan_type }}
          scan-ref: ${{ inputs.scan_ref }}
          severity: ${{ inputs.severity }
          exit-code: ${{ inputs.exit_code }
          ignore-unfixed: ${{ inputs.ignore_unfixed }
        env:
          TRIVY_DB_REPOSITORY: ${{ inputs.trivy_db_repository }}
          TRIVY_JAVA_DB_REPOSITORY: ${{ inputs.trivy_java_db_repository }}
