// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFeatureFlagRequestAdapter creates a new instance of MockFeatureFlagRequestAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureFlagRequestAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureFlagRequestAdapter {
	mock := &MockFeatureFlagRequestAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureFlagRequestAdapter is an autogenerated mock type for the FeatureFlagRequestAdapter type
type MockFeatureFlagRequestAdapter struct {
	mock.Mock
}

type MockFeatureFlagRequestAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureFlagRequestAdapter) EXPECT() *MockFeatureFlagRequestAdapter_Expecter {
	return &MockFeatureFlagRequestAdapter_Expecter{mock: &_m.Mock}
}

// IsEnabled provides a mock function for the type MockFeatureFlagRequestAdapter
func (_mock *MockFeatureFlagRequestAdapter) IsEnabled(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFeatureFlagRequestAdapter_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockFeatureFlagRequestAdapter_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFeatureFlagRequestAdapter_Expecter) IsEnabled(ctx interface{}, key interface{}) *MockFeatureFlagRequestAdapter_IsEnabled_Call {
	return &MockFeatureFlagRequestAdapter_IsEnabled_Call{Call: _e.mock.On("IsEnabled", ctx, key)}
}

func (_c *MockFeatureFlagRequestAdapter_IsEnabled_Call) Run(run func(ctx context.Context, key string)) *MockFeatureFlagRequestAdapter_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeatureFlagRequestAdapter_IsEnabled_Call) Return(b bool, err error) *MockFeatureFlagRequestAdapter_IsEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFeatureFlagRequestAdapter_IsEnabled_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockFeatureFlagRequestAdapter_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleFlag provides a mock function for the type MockFeatureFlagRequestAdapter
func (_mock *MockFeatureFlagRequestAdapter) ToggleFlag(response http.ResponseWriter, request *http.Request) {
	_mock.Called(response, request)
	return
}

// MockFeatureFlagRequestAdapter_ToggleFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleFlag'
type MockFeatureFlagRequestAdapter_ToggleFlag_Call struct {
	*mock.Call
}

// ToggleFlag is a helper method to define mock.On call
//   - response http.ResponseWriter
//   - request *http.Request
func (_e *MockFeatureFlagRequestAdapter_Expecter) ToggleFlag(response interface{}, request interface{}) *MockFeatureFlagRequestAdapter_ToggleFlag_Call {
	return &MockFeatureFlagRequestAdapter_ToggleFlag_Call{Call: _e.mock.On("ToggleFlag", response, request)}
}

func (_c *MockFeatureFlagRequestAdapter_ToggleFlag_Call) Run(run func(response http.ResponseWriter, request *http.Request)) *MockFeatureFlagRequestAdapter_ToggleFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFeatureFlagRequestAdapter_ToggleFlag_Call) Return() *MockFeatureFlagRequestAdapter_ToggleFlag_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFeatureFlagRequestAdapter_ToggleFlag_Call) RunAndReturn(run func(response http.ResponseWriter, request *http.Request)) *MockFeatureFlagRequestAdapter_ToggleFlag_Call {
	_c.Run(run)
	return _c
}
